#!/usr/bin/env node
/**
 * Seed script for Familjen Frosts Kokbok
 * Usage: node supabase/seed.mjs <family_id>
 *
 * If no family_id given, lists available families.
 */

const SUPABASE_URL = "https://znpjchdmshvdzmwjfbfw.supabase.co";
const SERVICE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpucGpjaGRtc2h2ZHptd2pmYmZ3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTgzODkyOCwiZXhwIjoyMDkxNDE0OTI4fQ.5WPMhDRUXebeGYfwGG84L6GIi9GS4CWyEczbuJK4_4I";

const headers = {
  apikey: SERVICE_KEY,
  Authorization: `Bearer ${SERVICE_KEY}`,
  "Content-Type": "application/json",
  Prefer: "return=representation",
};

async function api(path, body) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
    method: "POST",
    headers,
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`${res.status} ${path}: ${text}`);
  }
  return res.json();
}

async function listFamilies() {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/families?select=id,name`, {
    headers,
  });
  return res.json();
}

// ── All recipes ──────────────────────────────────────────────
const recipes = [
  // ═══ FÖRRÄTTER OCH TILLTUGG ═══
  {
    title: "Aubergineröra",
    category: "Förrätter",
    description: "Extra gott med knapriga rädisor och eventuellt lite extra salt till.",
    servings: 8,
    instructions: "1. Sätt ugnen på 225°. Picka auberginerna med en gaffel och lägg dem hela i ugnen.\n2. Låt auberginerna bakas i ugnen i cirka 45-60 min tills de är helt mjuka. Ta ut dem och dela på mitten. Gröp ur köttet och dela i mindre bitar, lägg det i ett finmaskigt durkslag.\n3. Låt rinna av i cirka en halv timme. Rör runt emellanåt.\n4. Lägg sedan bitarna i en mixer tillsammans med övriga ingredienser och kör till en jämn smet. Salta och peppra efter egen smak. Ställ övertäckt i kylen tills den ska ätas.",
    ingredients: [
      { ingredient: "Auberginer", amount: "3-4", unit: "st" },
      { ingredient: "Färskpressad citronjuice", amount: "1", unit: "st" },
      { ingredient: "Chèvre, fransk getost", amount: "100", unit: "g" },
      { ingredient: "Vitlöksklyftor, krossade", amount: "3", unit: "st" },
      { ingredient: "Olivolja", amount: "2-3", unit: "msk" },
      { ingredient: "Salt och peppar", amount: null, unit: null },
      { ingredient: "Persilja", amount: null, unit: null },
    ],
  },
  {
    title: "Chili rellenos",
    category: "Förrätter",
    description: "Små chilifrukter fyllda med ost. Knaprigt, eldigt och perfekt till burgare.",
    servings: 4,
    instructions: "Skär ett snitt i chilifrukterna på längden och kärna ur dem. Blanda riven ost med färskost till en kräm. Fördela ostkrämen i chilifrukterna. Vispa ihop ingredienserna till frityrsmeten. Värm smöret till ca 140°. Doppa chilifrukterna i frityrsmeten och vänd dem i panko. Fritera ca 1½ min på varje sida.",
    ingredients: [
      { ingredient: "Färska gröna jalapeños", amount: "12", unit: "st" },
      { ingredient: "Cheddar, riven", amount: "3", unit: "dl" },
      { ingredient: "Färskost", amount: "150", unit: "g" },
      { ingredient: "Majsstärkelse", amount: "3", unit: "dl" },
      { ingredient: "Ägg", amount: "1", unit: "st" },
      { ingredient: "Salt", amount: "1½", unit: "tsk" },
      { ingredient: "Bakpulver", amount: "½", unit: "tsk" },
      { ingredient: "Mineralvatten", amount: "1", unit: "dl" },
      { ingredient: "Klarifierat smör", amount: "250", unit: "g" },
      { ingredient: "Panko", amount: "2", unit: "dl" },
    ],
  },
  {
    title: "Chili Snacks med räkor",
    category: "Förrätter",
    description: "Snabba och lätta snacks.",
    servings: null,
    instructions: "Blanda ner pressad vitlök, rivet limeskal och ½ msk saft i olivoljan. Marinera räkorna i olivolja i ca 30 min. Sila av oljan. Klicka cottage cheese på nachos. Lägg på räkor och färska korianderblad.",
    ingredients: [
      { ingredient: "Vitlöksklyfta", amount: "1", unit: "st" },
      { ingredient: "Lime", amount: "1", unit: "st" },
      { ingredient: "Olivolja", amount: "3/4", unit: "dl" },
      { ingredient: "Skalade räkor", amount: "150", unit: "g" },
      { ingredient: "Cottage cheese, chili", amount: "250", unit: "g" },
      { ingredient: "Nachos", amount: null, unit: null },
      { ingredient: "Färska korianderblad", amount: null, unit: null },
    ],
  },
  {
    title: "Curry kyckling gratäng",
    category: "Förrätter",
    description: null,
    servings: null,
    instructions: "Stek löken i lite smör. Ta i curryn och stek kort. Rör i mjölk och grädde. Lägg sedan i paprikorna och koka dem mjuka. Red såsen lagom simmig. Lägg i kycklingen och koka upp.\nLägg över kokt pasta i ugnsform. Toppa med räkor och ost. Gratinera!",
    ingredients: [
      { ingredient: "Bandpasta", amount: "½", unit: "pkt" },
      { ingredient: "Grillad kyckling i bitar", amount: "1", unit: "st" },
      { ingredient: "Paprika (2 gröna, 1 röd)", amount: "3", unit: "st" },
      { ingredient: "Gula lökar", amount: "1-2", unit: "st" },
      { ingredient: "Madras curry", amount: "2", unit: "msk" },
      { ingredient: "Kinesisk soja", amount: "½", unit: "dl" },
      { ingredient: "Grädde", amount: "8", unit: "dl" },
      { ingredient: "Mjölk", amount: "3", unit: "dl" },
      { ingredient: "Räkor", amount: "1", unit: "pkt" },
      { ingredient: "Riven ost", amount: null, unit: null },
    ],
  },
  {
    title: "Het ananas- & mangosalsa",
    category: "Förrätter",
    description: "Fruktig och örtig.",
    servings: 4,
    instructions: "Blanda fintärnad färsk ananas, tinad mango i tärningar och strimlade salladslökar. Tillsätt urkärnad, finhackad röd chili, finrivet skal och pressad juice av lime, olivolja, finhackad citronmeliss och finhackad koriander. Krydda med salt.",
    ingredients: [
      { ingredient: "Färsk ananas", amount: "250", unit: "g" },
      { ingredient: "Tinad mango", amount: "250", unit: "g" },
      { ingredient: "Salladslökar", amount: "2", unit: "st" },
      { ingredient: "Röd chili", amount: "1", unit: "st" },
      { ingredient: "Lime", amount: "½", unit: "st" },
      { ingredient: "Olivolja", amount: "1", unit: "msk" },
      { ingredient: "Citronmeliss", amount: "½", unit: "kruka" },
      { ingredient: "Koriander", amount: "½", unit: "kruka" },
      { ingredient: "Salt", amount: "1", unit: "krm" },
    ],
  },
  {
    title: "Minifritters",
    category: "Förrätter",
    description: "Med Västerbottenost toppade med smetana och stenbitsrom.",
    servings: 10,
    instructions: "Blanda ihop västerbottenost, pankoströbröd, ägg, vitlökspulver, salt och peppar. Forma smeten till 8-10 bollar och platta till. Hetta upp lite olja och stek ca 2-3 minuter per sida. Toppa med smetana, stenbitsrom, rödlök och dill.",
    ingredients: [
      { ingredient: "Pankoströbröd", amount: "2", unit: "dl" },
      { ingredient: "Ägg", amount: "2", unit: "st" },
      { ingredient: "Vitlökspulver", amount: "½", unit: "tsk" },
      { ingredient: "Salt", amount: null, unit: null },
      { ingredient: "Svartpeppar", amount: null, unit: null },
      { ingredient: "Olja och smör till stekning", amount: null, unit: null },
    ],
  },
  {
    title: "Mousse de roquefort",
    category: "Förrätter",
    description: null,
    servings: null,
    instructions: "Häll crème fraîche i en kyld bunke, tillsätt 2 msk iskallt vatten. Vispa tills det blir en luftig smet. Hacka sönder smöret och osten i små bitar, och mixa detta. Tillsätt sedan crème fraichen och de hackade valnötterna och blanda ihop. Servera gärna till franskt rostat lantbröd.",
    ingredients: [
      { ingredient: "Roquefort", amount: "100", unit: "g" },
      { ingredient: "Crème fraîche", amount: "100", unit: "g" },
      { ingredient: "Smör", amount: "100", unit: "g" },
      { ingredient: "Valnötter", amount: "50", unit: "g" },
    ],
  },
  {
    title: "Salamichips",
    category: "Förrätter",
    description: "Kul och krispigt till drinken.",
    servings: null,
    instructions: "Sätt ugnen på 200°C. Lägg tunna salamiskivor på bakpappersklädda plåtar. Ställ in i ugnen 8-10 minuter tills de är krispiga. Låt svalna. Blanda smetana med finrivet citronskal, salt och svartpeppar. Klicka på smetana och strö krossad rosépeppar över.",
    ingredients: [
      { ingredient: "Tunna salamiskivor", amount: "35", unit: "st" },
      { ingredient: "Smetana", amount: "1½", unit: "dl" },
      { ingredient: "Finrivet citronskal", amount: "1", unit: "msk" },
      { ingredient: "Salt", amount: "1", unit: "krm" },
      { ingredient: "Svartpeppar", amount: "1", unit: "krm" },
      { ingredient: "Krossad rosépeppar", amount: null, unit: null },
    ],
  },

  // ═══ HUVUDRÄTTER ═══
  {
    title: "Alex godaste gryta",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions: "1. Koka det brynta köttet med den brynta gula löken och vitlöken i vatten, fond, buljong med lagerbladet, tomatpurén, 1 morot, rotselleri/fänkål, timjan, svartpeppar samt lite balsamvinäger i 1-1,5 timmar.\n2. Tag upp köttet och lagerbladet och mixa buljongen & grönsakerna slätt. Lägg i lite kött, 2 morötter, rotselleri samt stekta smålökar och stekta champinjoner. Smaka av med svartpeppar och ev rödvin. Koka i 15-20 min till.",
    ingredients: [
      { ingredient: "Grytbitar", amount: "1", unit: "kg" },
      { ingredient: "Gul lök, hackad", amount: "1", unit: "st" },
      { ingredient: "Morötter i slantar", amount: "3", unit: "st" },
      { ingredient: "Lagerblad", amount: "1", unit: "st" },
      { ingredient: "Tomatpuré", amount: "4", unit: "msk" },
      { ingredient: "Vitlöksklyftor, hackade", amount: "2", unit: "st" },
      { ingredient: "Smålökar", amount: "1", unit: "gäng" },
      { ingredient: "Champinjoner", amount: "1", unit: "gäng" },
      { ingredient: "Rotselleri", amount: "1", unit: "bit" },
      { ingredient: "Timjan", amount: null, unit: null },
      { ingredient: "Vatten", amount: "1", unit: "liter" },
      { ingredient: "Rödvinsfond", amount: "½", unit: "dl" },
      { ingredient: "Mörk oxbuljong", amount: "1-2", unit: "tärningar" },
      { ingredient: "Balsamvinäger", amount: null, unit: null },
    ],
  },
  {
    title: "Alex's chili con carne",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions: "Stek lök, vitlök, chili och timjan i en gryta. Stek köttet separat och lägg i. Tillsätt alla kryddor och tomat, bacon samt tomatpuré, köttbuljong och vatten. Låt koka i 10 minuter. Tillsätt paprika och soja, koka 10 minuter till. Häll i bönor och koka 5 minuter till. Servera med ris eller gräddfil.",
    ingredients: [
      { ingredient: "Bacon", amount: "1", unit: "pkt" },
      { ingredient: "Stora lökar, hackade", amount: "2", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: null, unit: null },
      { ingredient: "Chili, hackad", amount: null, unit: null },
      { ingredient: "Färsk timjan", amount: "1", unit: "kvist" },
      { ingredient: "Nötfärs", amount: "500", unit: "g" },
      { ingredient: "Spiskummin", amount: "1", unit: "tsk" },
      { ingredient: "Oregano", amount: "1", unit: "tsk" },
      { ingredient: "Paprikapulver", amount: "2", unit: "tsk" },
      { ingredient: "Hela tomater", amount: "1", unit: "burk" },
      { ingredient: "Krossade tomater", amount: "1", unit: "burk" },
      { ingredient: "Tomatpuré", amount: "2", unit: "msk" },
      { ingredient: "Köttbuljongtärning", amount: "1-2", unit: "st" },
      { ingredient: "Kidneybönor", amount: "1", unit: "burk" },
      { ingredient: "Vita bönor", amount: "2", unit: "burkar" },
      { ingredient: "Salt & peppar", amount: null, unit: null },
    ],
  },
  {
    title: "Alexs citronpasta med skaldjur",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions: "Koka pastan. Fräs vitlök och lök i några minuter. Tillsätt citronskal och vin. Häll i grädde, crème fraiche och buljong och örter. Koka ihop. Smaka av med salt och peppar. Ta av värmen och häll i kräftstjärtar och räkor. Servera med parmesan.",
    ingredients: [
      { ingredient: "Bandpasta", amount: "400", unit: "g" },
      { ingredient: "Vitlöksklyftor", amount: "1-2", unit: "st" },
      { ingredient: "Gula lökar", amount: "2", unit: "st" },
      { ingredient: "Rivet citronskal", amount: "1", unit: "citron" },
      { ingredient: "Vitt vin", amount: "2", unit: "dl" },
      { ingredient: "Vispgrädde", amount: "5", unit: "dl" },
      { ingredient: "Crème fraiche", amount: "1", unit: "burk" },
      { ingredient: "Fiskfond", amount: "3-4", unit: "msk" },
      { ingredient: "Kräftstjärtar", amount: "1", unit: "burk" },
      { ingredient: "Räkor med skal", amount: "500", unit: "g" },
      { ingredient: "Persilja, dragon, dill, gräslök", amount: null, unit: null },
    ],
  },
  {
    title: "Biff stroganoff",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions: "1. Skär köttet i strimlor. Skala och hacka löken. Skiva champinjonerna.\n2. Bryn matfettet. Stek köttet hastigt. Minska värmen, lägg i löken och champinjonerna.\n3. Krydda med salt, peppar och paprikapulver. Tillsätt tomatpurén, senapen och späd med grädden.\n4. Efterstek under lock ca 10 min. Häll i gräddfilen. Låt ej koka.",
    ingredients: [
      { ingredient: "Innanlår eller biff", amount: "500", unit: "g" },
      { ingredient: "Gul lök", amount: "1", unit: "st" },
      { ingredient: "Färska champinjoner", amount: "150", unit: "g" },
      { ingredient: "Smör", amount: "2", unit: "msk" },
      { ingredient: "Salt", amount: "½", unit: "tsk" },
      { ingredient: "Peppar", amount: "1", unit: "krm" },
      { ingredient: "Paprikapulver", amount: "2", unit: "krm" },
      { ingredient: "Tomatpuré", amount: "4", unit: "msk" },
      { ingredient: "Fransk senap", amount: "2", unit: "tsk" },
      { ingredient: "Grädde", amount: "1½", unit: "dl" },
      { ingredient: "Gräddfil", amount: "1½", unit: "dl" },
    ],
  },
  {
    title: "Boeuf Bourguignon",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions: "Stek lök och vitlök. Stek köttet i olja och smör, lite i taget. Stek bacon och sedan svampen. Lägg allt i en gryta med rödvin, grönsakerna, kryddor, tomater och ca 1 liter vatten. Koka tills köttet är mört.",
    ingredients: [
      { ingredient: "Grytbitar", amount: "1,5", unit: "kg" },
      { ingredient: "Rödvin", amount: "5", unit: "dl" },
      { ingredient: "Bacon, hackat", amount: "1", unit: "pkt" },
      { ingredient: "Gula lökar, hackade", amount: "2", unit: "st" },
      { ingredient: "Vitlöksklyftor, hackade", amount: "3", unit: "st" },
      { ingredient: "Morötter", amount: "2", unit: "st" },
      { ingredient: "Palsternacka", amount: "1", unit: "st" },
      { ingredient: "Rotselleri", amount: "1", unit: "bit" },
      { ingredient: "Champinjoner", amount: null, unit: null },
      { ingredient: "Mörk oxbuljongtärning", amount: "1", unit: "st" },
      { ingredient: "Köttbuljongtärningar", amount: "3", unit: "st" },
      { ingredient: "Hela tomater i bitar", amount: "½-1", unit: "burk" },
      { ingredient: "Grönpeppar", amount: "1-2", unit: "msk" },
      { ingredient: "Grädde", amount: "2", unit: "dl" },
      { ingredient: "Choklad", amount: "2", unit: "rutor" },
      { ingredient: "Balsamvinäger", amount: "1", unit: "msk" },
      { ingredient: "Lagerblad", amount: "2", unit: "st" },
      { ingredient: "Timjan", amount: null, unit: null },
    ],
  },
  {
    title: "Chicken tikka masala",
    category: "Huvudrätter",
    description: null,
    servings: 12,
    instructions: "1. Mät upp riset med dubbla mängden vatten, kanelstång, kardemumma och gurkmeja. Koka upp.\n2. Bryn kycklingen. Tillsätt vitlök och hackade grönsaker. Krydda med garam masala, koriander och ingefära. Häll i grädden och tomatpurén.\n3. Raita: Strimla gurkan och blanda med yoghurt och mynta.\n4. Servera med kryddigt ris och raita.",
    ingredients: [
      { ingredient: "Kyckling", amount: "900", unit: "g" },
      { ingredient: "Röd chili, hackad", amount: "1,5", unit: "st" },
      { ingredient: "Grädde", amount: "9", unit: "dl" },
      { ingredient: "Salladslökar", amount: "9", unit: "st" },
      { ingredient: "Paprika", amount: "3", unit: "st" },
      { ingredient: "Tomatpuré", amount: "1½-2", unit: "burkar" },
      { ingredient: "Hackad ingefära", amount: "3", unit: "msk" },
      { ingredient: "Hackad koriander", amount: "1,5", unit: "dl" },
      { ingredient: "Vitlöksklyftor, hackade", amount: "3", unit: "st" },
      { ingredient: "Garam masala", amount: "6", unit: "tsk" },
      { ingredient: "Basmatiris", amount: "12", unit: "dl" },
      { ingredient: "Kanelstång", amount: "3", unit: "st" },
      { ingredient: "Gurkmeja", amount: "1", unit: "tsk" },
    ],
  },
  {
    title: "Chorizolasagne",
    category: "Huvudrätter",
    description: null,
    servings: 6,
    instructions: "1. Finhacka lök och vitlök. Riv morötterna. Fräs chorizo, tillsätt lök, vitlök och morot.\n2. Tillsätt krossade tomater och örter, koka ca 10 min.\n3. Ostsås: Smält smör, vispa ner mjöl. Tillsätt mjölk. Koka, rör ner ost.\n4. Varva chorizosås, lasagneplattor och ostsås. Toppa med ost. Ugn 200°C i 30-40 min.",
    ingredients: [
      { ingredient: "Gul lök", amount: "1", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "2", unit: "st" },
      { ingredient: "Morötter", amount: "2", unit: "st" },
      { ingredient: "Färsk chorizo", amount: "500", unit: "g" },
      { ingredient: "Krossade tomater", amount: "500", unit: "g" },
      { ingredient: "Torkade örter", amount: "2", unit: "tsk" },
      { ingredient: "Lasagneplattor", amount: "12", unit: "st" },
      { ingredient: "Riven ost", amount: "1", unit: "dl" },
      { ingredient: "Smör (ostsås)", amount: "25", unit: "g" },
      { ingredient: "Vetemjöl (ostsås)", amount: "1", unit: "dl" },
      { ingredient: "Mjölk (ostsås)", amount: "1", unit: "liter" },
    ],
  },
  {
    title: "Den fulländade spagetti bolognesen",
    category: "Huvudrätter",
    description: null,
    servings: 5,
    instructions: "1. Stek pancettan. Hacka lök, vitlök, morötter, selleri, zucchini och aubergine fint. Stek tills de blivit mjuka.\n2. Lägg i köttfärsen, rör runt. Slå på vinet, sänk värmen. Låt puttra 10 min.\n3. Häll i tomater, grädde, lagerblad och basilika. Låt puttra ca 1 timme. Smaka av och servera med spaghetti och parmesan.",
    ingredients: [
      { ingredient: "Olivolja", amount: "1", unit: "msk" },
      { ingredient: "Pancetta eller bacon", amount: "140", unit: "g" },
      { ingredient: "Gula lökar", amount: "2", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "4", unit: "st" },
      { ingredient: "Morot", amount: "1", unit: "st" },
      { ingredient: "Selleristjälk", amount: "1", unit: "st" },
      { ingredient: "Zucchini", amount: "1", unit: "liten" },
      { ingredient: "Aubergine", amount: "½", unit: "st" },
      { ingredient: "Nötfärs", amount: "1", unit: "kg" },
      { ingredient: "Rödvin", amount: "3", unit: "dl" },
      { ingredient: "Krossade tomater", amount: "2", unit: "burkar" },
      { ingredient: "Vispgrädde", amount: "2", unit: "dl" },
      { ingredient: "Lagerblad", amount: "2", unit: "st" },
      { ingredient: "Torkad basilika", amount: "1", unit: "msk" },
      { ingredient: "Spaghetti", amount: null, unit: null },
    ],
  },
  {
    title: "Potatisgratäng",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions: "Sätt ugnen på 175-200°. Hacka löken och potatisarna. Blanda alla ingredienser förutom osten i ugnsform. Grädda i minst 45 minuter och strö över osten efter halva tiden.",
    ingredients: [
      { ingredient: "Stora potatisar", amount: "4", unit: "st" },
      { ingredient: "Grädde", amount: "2", unit: "dl" },
      { ingredient: "Mjölk", amount: "1", unit: "dl" },
      { ingredient: "Gruyère ost", amount: "70-80", unit: "g" },
      { ingredient: "Vitlöksklyftor", amount: "1-2", unit: "st" },
      { ingredient: "Muskot", amount: null, unit: null },
      { ingredient: "Salt & peppar", amount: null, unit: null },
      { ingredient: "Gul lök", amount: "1", unit: "st" },
      { ingredient: "Purjolök", amount: "1", unit: "st" },
    ],
  },
  {
    title: "Quiche lorraine",
    category: "Huvudrätter",
    description: "En utmärkt lunchrätt som kan göras i förväg.",
    servings: 4,
    instructions: "1. Finfördela matfettet i mjölet. Tillsätt vatten, arbeta ihop degen. Vila i kylen 1 timme.\n2. Kavla ut degen i en form. Pricka botten. Grädda pajskalet i 250° ca 10 min.\n3. Vispa samman ägg och grädde. Tillsätt kryddor, skinka och ost. Häll i pajskalet. Grädda i 225° ca 15-20 min.",
    ingredients: [
      { ingredient: "Vetemjöl", amount: "3", unit: "dl" },
      { ingredient: "Smör", amount: "150", unit: "g" },
      { ingredient: "Vatten", amount: "2", unit: "msk" },
      { ingredient: "Ägg", amount: "3", unit: "st" },
      { ingredient: "Vispgrädde", amount: "3", unit: "dl" },
      { ingredient: "Herbes de Provence", amount: "1", unit: "tsk" },
      { ingredient: "Rökt skinka, strimlad", amount: "200", unit: "g" },
      { ingredient: "Riven ost", amount: "3-4", unit: "dl" },
    ],
  },
  {
    title: "Matig tacopaj",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions: "1. Ugn 200°. Blanda margarin med torra ingredienser, häll i mjölk, tryck ut i form.\n2. Stek köttfärs och lök, pressa i vitlök, tillsätt tacokrydda och vatten.\n3. Häll i pajskalet, lägg på tomater. Blanda crème fraiche, majonnäs och ost, bred ut över. Grädda 12-15 min.",
    ingredients: [
      { ingredient: "Vetemjöl", amount: "4", unit: "dl" },
      { ingredient: "Bakpulver", amount: "2", unit: "tsk" },
      { ingredient: "Salt", amount: "0,5", unit: "tsk" },
      { ingredient: "Margarin", amount: "50", unit: "g" },
      { ingredient: "Mjölk", amount: "1,5", unit: "dl" },
      { ingredient: "Köttfärs", amount: "500", unit: "g" },
      { ingredient: "Tacokrydda", amount: "1", unit: "påse" },
      { ingredient: "Vitlöksklyftor", amount: "2", unit: "st" },
      { ingredient: "Tomater", amount: "3", unit: "st" },
      { ingredient: "Crème fraiche", amount: "2", unit: "dl" },
      { ingredient: "Majonnäs", amount: "4", unit: "msk" },
      { ingredient: "Riven ost", amount: "2", unit: "dl" },
    ],
  },
  {
    title: "Pad krapow",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions: "Gör en pasté av den röda chilin och vitlöksklyftorna. Stek pastén i rikligt med rapsolja. Lägg i köttfärsen och stek. Stek med kryddorna. Woka alla grönsakerna separat och lägg i. Servera med ris och thaibasilika.",
    ingredients: [
      { ingredient: "Blandfärs/nötfärs", amount: "800", unit: "g" },
      { ingredient: "Röd chili", amount: "1", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "4", unit: "st" },
      { ingredient: "Fisksås", amount: "5", unit: "msk" },
      { ingredient: "Ostronsås", amount: "5", unit: "msk" },
      { ingredient: "Ljus japansk soja", amount: "3", unit: "msk" },
      { ingredient: "Socker", amount: "2", unit: "tsk" },
      { ingredient: "Rödlök + salladslök", amount: null, unit: null },
      { ingredient: "Paprika (gul + röd)", amount: "2", unit: "st" },
      { ingredient: "Broccoli", amount: "1", unit: "bunt" },
      { ingredient: "Morot i stavar", amount: "1", unit: "st" },
      { ingredient: "Bambuskott", amount: null, unit: null },
      { ingredient: "Färsk thaibasilika", amount: null, unit: null },
    ],
  },
  {
    title: "Paella",
    category: "Huvudrätter",
    description: "Saffransdoftande ris med kyckling, skaldjur och grönsaker.",
    servings: 6,
    instructions: "1. Dela kycklingen i bitar.\n2. Fräs lök och vitlök i olja.\n3. Tillsätt ris och saffran, späd med buljong. Sjud 20-25 min.\n4. Blanda ner kyckling, musslor, räkor, ärter och pimiento. Strö över persilja.",
    ingredients: [
      { ingredient: "Grillad kyckling", amount: "800", unit: "g" },
      { ingredient: "Olivolja", amount: "2", unit: "msk" },
      { ingredient: "Finhackad gul lök", amount: "3", unit: "msk" },
      { ingredient: "Vitlöksklyftor", amount: "2-3", unit: "st" },
      { ingredient: "Långkornigt ris", amount: "3", unit: "dl" },
      { ingredient: "Saffran", amount: "1", unit: "g" },
      { ingredient: "Buljong och musselspad", amount: "6", unit: "dl" },
      { ingredient: "Musslor", amount: "225", unit: "g" },
      { ingredient: "Skalade räkor", amount: "250", unit: "g" },
      { ingredient: "Ärter", amount: "250", unit: "g" },
      { ingredient: "Pimiento", amount: "1", unit: "burk" },
      { ingredient: "Persilja", amount: null, unit: null },
    ],
  },
  {
    title: "Yakiniku",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions: "Koka riset. Koka ihop soja, saké, mirin, vitlök, ingefära och sesamfrön till yakinikusås. Blanda ihop misosåsen. Koka edamame. Bryn köttet 2-3 min per sida, låt vila 5 min. Skiva tunt. Servera med salladsblad, misosås, ris och edamame.",
    ingredients: [
      { ingredient: "Ryggbiff, välmarmorerad", amount: "700", unit: "g" },
      { ingredient: "Japanskt ris", amount: "4", unit: "port" },
      { ingredient: "Edamamebönor", amount: "500", unit: "g" },
      { ingredient: "Japansk soja", amount: "6", unit: "msk" },
      { ingredient: "Mirin", amount: "6", unit: "msk" },
      { ingredient: "Sake", amount: "4", unit: "msk" },
      { ingredient: "Risvinäger", amount: "1", unit: "msk" },
      { ingredient: "Vitlök, riven", amount: "2", unit: "klyftor" },
      { ingredient: "Färsk ingefära, riven", amount: "4", unit: "cm" },
      { ingredient: "Rostade sesamfrön", amount: "1", unit: "msk" },
      { ingredient: "Majonnäs (kewpie)", amount: "2", unit: "dl" },
      { ingredient: "Vit misopasta", amount: "1", unit: "msk" },
      { ingredient: "Tahini pasta", amount: "1", unit: "msk" },
      { ingredient: "Sesamolja", amount: "1", unit: "msk" },
      { ingredient: "Huvudsallad", amount: "2", unit: "st" },
    ],
  },
  {
    title: "Österrikisk ostfondue",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions: "Pressa ner vitlöksklyfta i fonduegrytan och gnid ut. Häll på vinet och värm. Tillsätt den rivna osten lite i taget. Smält under ständig omrörning. Tillsätt muskot, peppar, ev Maizena och ytterligare vitlök. Avsluta med brännvin och citronsaft. Servera med brödtärningar.",
    ingredients: [
      { ingredient: "Ost (Appenzeller, Gruyère, Fontal, Fontina)", amount: "200", unit: "g/person" },
      { ingredient: "Vitt vin", amount: "0,5", unit: "dl/person" },
      { ingredient: "Vitlöksklyftor", amount: "2", unit: "st" },
      { ingredient: "Riven muskotnöt", amount: null, unit: null },
      { ingredient: "Peppar", amount: null, unit: null },
      { ingredient: "Maizena", amount: "1-2", unit: "tsk" },
      { ingredient: "Kirsch brännvin", amount: "½", unit: "glas" },
      { ingredient: "Citronjuice", amount: "1", unit: "tsk" },
      { ingredient: "Brödtärningar av vitt bröd", amount: null, unit: null },
    ],
  },

  // ═══ SÅSER MED MERA ═══
  {
    title: "Aioli",
    category: "Såser",
    description: null,
    servings: null,
    instructions: "Rör ihop ingredienserna med gaffel. Låt stå minst ½ timme i kylskåp. Rör ordentligt då och då.",
    ingredients: [
      { ingredient: "Äkta majonnäs", amount: "4", unit: "msk" },
      { ingredient: "Crème fraiche", amount: "1", unit: "msk" },
      { ingredient: "Vitlöksklyftor, pressade", amount: "3", unit: "st" },
      { ingredient: "Citronsaft", amount: null, unit: "droppar" },
      { ingredient: "Paprikapulver", amount: "1", unit: "kryddmått" },
      { ingredient: "Cayennepeppar", amount: "2", unit: "knivsuddar" },
    ],
  },
  {
    title: "Smör med fin kryddning",
    category: "Såser",
    description: "Härligt fluffigt och gott smör till köttet.",
    servings: 10,
    instructions: "Lägg alla ingredienser i matberedaren med strålkniven. Låt gå tills smöret är väl blandat och fluffigt. Lägg smöret i en skål och ställ kallt.",
    ingredients: [
      { ingredient: "Smör", amount: "200", unit: "g" },
      { ingredient: "Gul curry madras", amount: "2", unit: "krm" },
      { ingredient: "Äggula", amount: "1", unit: "st" },
      { ingredient: "Tomatpuré", amount: "1", unit: "msk" },
      { ingredient: "Ljus fransk senap", amount: "1", unit: "msk" },
      { ingredient: "Gräslök", amount: "2", unit: "msk" },
      { ingredient: "Persilja", amount: "2", unit: "msk" },
      { ingredient: "Grönpeppar", amount: "2", unit: "tsk" },
      { ingredient: "Dragon", amount: "1", unit: "tsk" },
      { ingredient: "Vitlöksklyfta, pressad", amount: "2", unit: "st" },
      { ingredient: "Salt", amount: "½", unit: "tsk" },
      { ingredient: "Cayennepeppar", amount: "¼", unit: "krm" },
    ],
  },

  // ═══ SOPPOR ═══
  {
    title: "Blomkålssoppa",
    category: "Soppor",
    description: null,
    servings: null,
    instructions: "Stek bacon så det får färg. Stek lök och svamp. Tillsätt allt annat och koka grönsakerna mjuka. Mixa soppan slät. Smaka av med salt & peppar. Späd med vatten om soppan är för tjock.",
    ingredients: [
      { ingredient: "Matlagningsgrädde", amount: "5", unit: "dl" },
      { ingredient: "Vatten", amount: "7", unit: "dl" },
      { ingredient: "Gul lök, hackad", amount: "1", unit: "st" },
      { ingredient: "Bacon, strimlad", amount: "1", unit: "pkt" },
      { ingredient: "Grönsaksbuljongtärningar", amount: "2", unit: "st" },
      { ingredient: "Svamp i skivor", amount: null, unit: null },
      { ingredient: "Blomkål", amount: "600", unit: "g" },
      { ingredient: "Potatisar i tärningar", amount: "2", unit: "st" },
      { ingredient: "Salt och peppar", amount: null, unit: null },
    ],
  },
  {
    title: "Champinjonsoppa",
    category: "Soppor",
    description: "Rikligt med grädde gör den extra rund och god.",
    servings: 6,
    instructions: "1. Grovhacka hälften av champinjonerna. Fräs med lök i smör.\n2. Tillsätt timjan, fond, grädde och mjölk. Koka ca 10 min.\n3. Mixa slät. Tillsätt resten av svampen. Koka 2-3 min. Red med majsstärkelse. Stek resterande svamp och toppa.",
    ingredients: [
      { ingredient: "Champinjoner", amount: "500", unit: "g" },
      { ingredient: "Gul lök", amount: "1", unit: "st" },
      { ingredient: "Torkad timjan", amount: "1", unit: "tsk" },
      { ingredient: "Konc grönsaksfond", amount: "½", unit: "dl" },
      { ingredient: "Vispgrädde", amount: "5", unit: "dl" },
      { ingredient: "Mjölk", amount: "5", unit: "dl" },
      { ingredient: "Majsstärkelse", amount: "1½", unit: "msk" },
      { ingredient: "Smör", amount: null, unit: null },
      { ingredient: "Salt och peppar", amount: null, unit: null },
    ],
  },
  {
    title: "Gratinerad löksoppa",
    category: "Soppor",
    description: "En rätt med fransk finess.",
    servings: 4,
    instructions: "1. Fräs löken i matfett tills den får färg. Strö över mjölet. Späd med vatten, lägg i buljong.\n2. Tillsätt kryddbukett, salt och peppar. Sjud 20 min. Häll i vinet.\n3. Häll i ugnsform. Täck med brödskivor och riven ost. Gratinera i 250°.",
    ingredients: [
      { ingredient: "Stora gula lökar", amount: "4", unit: "st" },
      { ingredient: "Smör", amount: "2", unit: "msk" },
      { ingredient: "Vetemjöl", amount: "2", unit: "msk" },
      { ingredient: "Vatten", amount: "1", unit: "l" },
      { ingredient: "Grönsaksbuljongtärningar", amount: "1-2", unit: "st" },
      { ingredient: "Timjan, persilja, lagerblad", amount: null, unit: null },
      { ingredient: "Vitt vin", amount: "1½", unit: "dl" },
      { ingredient: "Vitt formbröd", amount: "4", unit: "skivor" },
      { ingredient: "Riven ost", amount: "2", unit: "dl" },
    ],
  },
  {
    title: "Kokossoppa med lax och ingefära",
    category: "Soppor",
    description: "En härligt kryddig soppa som ger svett på pannan.",
    servings: null,
    instructions: "1. Hacka schalottenlök, vitlök och chili. Fräs löken i olja. Tillsätt chili, citrongräs, gurkmeja och ingefära.\n2. Tillsätt limeskal, limesaft, fisksås, chilisås och socker. Häll i buljong och kokosmjölk.\n3. Tillsätt laxen, koka 10 min. Lägg i svamp, puttra 5 min. Smaka av.",
    ingredients: [
      { ingredient: "Schalottenlök", amount: "1", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "2", unit: "st" },
      { ingredient: "Grön chili", amount: "1", unit: "st" },
      { ingredient: "Citrongräs", amount: "1", unit: "strå" },
      { ingredient: "Olivolja", amount: "1", unit: "tsk" },
      { ingredient: "Gurkmeja", amount: "1", unit: "tsk" },
      { ingredient: "Ingefära", amount: "40", unit: "g" },
      { ingredient: "Limefrukter", amount: "2", unit: "st" },
      { ingredient: "Fisksås", amount: "3", unit: "msk" },
      { ingredient: "Stark chilisås", amount: "2", unit: "tsk" },
      { ingredient: "Muscovadosocker", amount: "2", unit: "msk" },
      { ingredient: "Grönsaksbuljong", amount: "1", unit: "liter" },
      { ingredient: "Kokosmjölk", amount: "2", unit: "burkar" },
      { ingredient: "Lax", amount: "600", unit: "g" },
      { ingredient: "Champinjoner", amount: "250", unit: "g" },
    ],
  },
  {
    title: "Tomatsoppa med ricottagnocchi",
    category: "Soppor",
    description: null,
    servings: 4,
    instructions: "Fräs lök och vitlök. Tillsätt salvia, tomater, vatten, buljong och honung. Koka 5 min. Mixa slät. Rör ihop gnocchi-ingredienserna. Forma bollar, sjud tills de flyter upp. Servera med brödsmulor.",
    ingredients: [
      { ingredient: "Gul lök", amount: "1", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "2", unit: "st" },
      { ingredient: "Olivolja", amount: "2", unit: "msk" },
      { ingredient: "Torkad salvia", amount: "1", unit: "msk" },
      { ingredient: "Tomater (hela eller krossade)", amount: "400", unit: "g" },
      { ingredient: "Vatten", amount: "5", unit: "dl" },
      { ingredient: "Grönsaksbuljongtärningar", amount: "2", unit: "st" },
      { ingredient: "Honung", amount: "1", unit: "tsk" },
      { ingredient: "Ricottaost", amount: "1", unit: "dl" },
      { ingredient: "Riven parmesanost", amount: "2", unit: "dl" },
      { ingredient: "Ägg", amount: "1", unit: "st" },
      { ingredient: "Vetemjöl", amount: "½", unit: "dl" },
      { ingredient: "Rivet citronskal", amount: "½", unit: "citron" },
    ],
  },

  // ═══ EFTERRÄTTER ═══
  {
    title: "Evas Kladdkaka",
    category: "Efterrätter",
    description: null,
    servings: null,
    instructions: "1. Ugn 175°C. Smält chokladen med smör. Vispa ägg, socker och vaniljsocker pösigt. Rör i mjöl, nötter och chokladblandningen. Tillsätt grovhackad choklad.\n2. Häll i form (ca 24 cm). Grädda ca 30 min. Kakan ska vara kletig i mitten. Låt svalna, gärna över natten i kylskåp.",
    ingredients: [
      { ingredient: "Mörk choklad 70%", amount: "300", unit: "g" },
      { ingredient: "Smör", amount: "300", unit: "g" },
      { ingredient: "Ägg", amount: "4", unit: "st" },
      { ingredient: "Strösocker", amount: "4", unit: "dl" },
      { ingredient: "Vaniljsocker", amount: "2", unit: "tsk" },
      { ingredient: "Vetemjöl", amount: "3", unit: "dl" },
      { ingredient: "Grovhackade nötter", amount: "100", unit: "g" },
      { ingredient: "Grovhackad choklad (blandad)", amount: "50-100", unit: "g" },
    ],
  },
  {
    title: "Hallonsmulpaj",
    category: "Efterrätter",
    description: null,
    servings: null,
    instructions: "Blanda ihop smält smör, vetemjöl, socker, havregryn och vaniljsocker till en deg. Lägg hallon i en tät form. Strö över potatismjöl och socker, lägg på pajdegen. Grädda i 225° i 25-30 min.",
    ingredients: [
      { ingredient: "Smält smör", amount: "200", unit: "g" },
      { ingredient: "Vetemjöl", amount: "2", unit: "dl" },
      { ingredient: "Socker", amount: "2", unit: "dl" },
      { ingredient: "Havregryn", amount: "4-5", unit: "dl" },
      { ingredient: "Vaniljsocker", amount: "2", unit: "tsk" },
      { ingredient: "Potatismjöl", amount: null, unit: null },
      { ingredient: "Hallon", amount: null, unit: null },
    ],
  },

  // ═══ BAKVERK OCH BRÖD ═══
  {
    title: "Bullar",
    category: "Bakverk",
    description: null,
    servings: 36,
    instructions: "Smält smöret. Blanda ner mjölk, salt, socker. Finfördela jästen och häll degspadet över. Tillsätt mjölet och arbeta till en smidig deg. Jäs 45 min. Kavla ut, bred på fyllning, rulla ihop, skär i bitar. Jäs 40 min. Pensla med ägg, strö pärlsocker. Grädda 250° i ca 8 min.",
    ingredients: [
      { ingredient: "Smör", amount: "150", unit: "g" },
      { ingredient: "Mjölk", amount: "5", unit: "dl" },
      { ingredient: "Salt", amount: "1", unit: "krm" },
      { ingredient: "Strösocker", amount: "1,5", unit: "dl" },
      { ingredient: "Jäst", amount: "50", unit: "g" },
      { ingredient: "Vetemjöl", amount: "14-15", unit: "dl" },
      { ingredient: "Ägg till pensling", amount: null, unit: null },
      { ingredient: "Pärlsocker", amount: null, unit: null },
    ],
  },
  {
    title: "Chokladbollar",
    category: "Bakverk",
    description: null,
    servings: null,
    instructions: "Blanda alla ingredienser förutom kokosflingor till smet. Forma bollar och rulla i kokosflingor. Ställ i kylen.",
    ingredients: [
      { ingredient: "Smör", amount: "100", unit: "g" },
      { ingredient: "Socker", amount: "1½", unit: "dl" },
      { ingredient: "Kakao", amount: "5", unit: "msk" },
      { ingredient: "Vaniljsocker", amount: "1", unit: "tsk" },
      { ingredient: "Kaffe", amount: "1-2", unit: "msk" },
      { ingredient: "Havregryn", amount: "5", unit: "dl" },
      { ingredient: "Kokosflingor", amount: null, unit: null },
    ],
  },
  {
    title: "Farmors äppelkakor",
    category: "Bakverk",
    description: null,
    servings: null,
    instructions: "Skala och klyfta äpplena tunt. Lägg i påse med kanel och socker, skaka. Rör ihop alla ingredienser till smeten. Häll smeten på bakplåt. Stick i äppelbitarna och strö över mandelspån. Baka 175° i 30 min.",
    ingredients: [
      { ingredient: "Äpplen", amount: "8", unit: "st" },
      { ingredient: "Kanel", amount: "2", unit: "msk" },
      { ingredient: "Strösocker (äpplen)", amount: "4", unit: "msk" },
      { ingredient: "Smält smör", amount: "200", unit: "g" },
      { ingredient: "Strösocker (smet)", amount: "5", unit: "dl" },
      { ingredient: "Vetemjöl", amount: "5", unit: "dl" },
      { ingredient: "Ägg", amount: "2", unit: "st" },
      { ingredient: "Vaniljsocker", amount: "2", unit: "msk" },
      { ingredient: "Mandelspån", amount: "1", unit: "påse" },
    ],
  },
  {
    title: "Focaccia Bröd",
    category: "Bakverk",
    description: null,
    servings: 25,
    instructions: "Finfördela jästen. Ljumma mjölken. Tillsätt salt, olivolja och vetemjöl. Arbeta till en smidig deg. Jäs 40 min. Häll i smord långpanna, tryck ut. Jäs 35 min. Tryck ner fingertopparna. Pensla med olivolja, strö salt och rosmarin. Grädda 200° i 20-25 min.",
    ingredients: [
      { ingredient: "Jäst", amount: "50", unit: "g" },
      { ingredient: "Lättmjölk", amount: "6", unit: "dl" },
      { ingredient: "Salt", amount: "1½", unit: "tsk" },
      { ingredient: "Olivolja", amount: "½", unit: "dl" },
      { ingredient: "Vetemjöl", amount: "13-14", unit: "dl" },
      { ingredient: "Olivolja (garnering)", amount: "½", unit: "dl" },
      { ingredient: "Gourmetsalt", amount: "½", unit: "msk" },
      { ingredient: "Rosmarin", amount: null, unit: null },
    ],
  },
  {
    title: "Godaste lussebullen",
    category: "Bakverk",
    description: null,
    servings: null,
    instructions: "1. Lägg saffran i rom/vatten, låt stå 30 min. Smula jästen, blanda med mjölk, smör och saffran.\n2. Tillsätt socker, salt och mjöl. Arbeta 15 min. Jäs 60 min.\n3. Baka ut till lussebullar. Jäs 30 min. Tryck i russin. Pensla med ägg. Grädda 225°C i 8-10 min.",
    ingredients: [
      { ingredient: "Saffran", amount: "1½", unit: "g" },
      { ingredient: "Rom eller vatten", amount: "2", unit: "msk" },
      { ingredient: "Jäst", amount: "50", unit: "g" },
      { ingredient: "Smör, rumsvarmt", amount: "175", unit: "g" },
      { ingredient: "Mjölk, rumsvarm", amount: "5", unit: "dl" },
      { ingredient: "Socker", amount: "2", unit: "dl" },
      { ingredient: "Salt", amount: "½", unit: "tsk" },
      { ingredient: "Vetemjöl", amount: "800", unit: "g" },
      { ingredient: "Russin", amount: "1", unit: "dl" },
    ],
  },
  {
    title: "Knådfritt Grytbröd",
    category: "Bakverk",
    description: null,
    servings: null,
    instructions: "Lös upp jästen i vattnet. Tillsätt resterande ingredienser. Rör ihop en jämn deg. Jäs 2 timmar. Sätt en gjutjärnsgryta i ugn på 250°. Stjälp upp degen, forma. Lägg i grytan. Sänk till 225°, grädda med lock 20 min. Ta av lock, grädda 20 min till.",
    ingredients: [
      { ingredient: "Jäst", amount: "25", unit: "g" },
      { ingredient: "Kallt vatten", amount: "5", unit: "dl" },
      { ingredient: "Olivolja", amount: "½", unit: "dl" },
      { ingredient: "Vetemjöl", amount: "11", unit: "dl" },
      { ingredient: "Salt", amount: "2", unit: "tsk" },
    ],
  },
  {
    title: "Mormors mörka chokladtårta",
    category: "Bakverk",
    description: null,
    servings: null,
    instructions: "Botten: Vispa äggvitorna hårt. Blanda med sötmandel och socker. Häll i form, grädda 150-160° ca 1 timme.\nKräm: Värm äggulor med socker och mjölk under ständig omrörning. Tillsätt choklad och smör. Bred ut krämen på botten. Vid servering, bred ut vispad grädde och strö riven choklad.",
    ingredients: [
      { ingredient: "Äggvitor (botten)", amount: "4", unit: "st" },
      { ingredient: "Mald sötmandel", amount: "100", unit: "g" },
      { ingredient: "Socker (botten)", amount: "1½", unit: "dl" },
      { ingredient: "Äggulor (kräm)", amount: "4", unit: "st" },
      { ingredient: "Socker (kräm)", amount: "1", unit: "dl" },
      { ingredient: "Mjölk", amount: "1", unit: "dl" },
      { ingredient: "Mörk blockchoklad", amount: "75", unit: "g" },
      { ingredient: "Smör", amount: "100", unit: "g" },
      { ingredient: "Vispgrädde (servering)", amount: "1½", unit: "dl" },
    ],
  },
  {
    title: "Morotsrulltårta",
    category: "Bakverk",
    description: null,
    servings: 10,
    instructions: "1. Ugn 225°C. Vispa ägg och socker fluffigt. Blanda torra ingredienser. Rör ner morötter och olja, sedan de torra.\n2. Bred ut på plåt. Grädda 5-7 min.\n3. Vänd ut kakan. Frosting: Vispa ihop smör, florsocker, vaniljsocker och färskost. Bred ut och rulla ihop.",
    ingredients: [
      { ingredient: "Ägg", amount: "2", unit: "st" },
      { ingredient: "Strösocker", amount: "2", unit: "dl" },
      { ingredient: "Vetemjöl", amount: "2", unit: "dl" },
      { ingredient: "Vaniljsocker", amount: "1½", unit: "tsk" },
      { ingredient: "Kanel", amount: "1", unit: "tsk" },
      { ingredient: "Malen ingefära", amount: "½", unit: "tsk" },
      { ingredient: "Bikarbonat", amount: "1", unit: "tsk" },
      { ingredient: "Bakpulver", amount: "1", unit: "tsk" },
      { ingredient: "Finrivna morötter", amount: "2", unit: "dl" },
      { ingredient: "Rapsolja", amount: "¾", unit: "dl" },
      { ingredient: "Smör (frosting)", amount: "75", unit: "g" },
      { ingredient: "Florsocker (frosting)", amount: "1½", unit: "dl" },
      { ingredient: "Färskost (frosting)", amount: "300", unit: "g" },
    ],
  },

  // ═══ ÖVRIGT ═══
  {
    title: "Kräftlag",
    category: "Övrigt",
    description: "För omkok av 1 pkt.",
    servings: null,
    instructions: "Koka upp ingredienserna och låt koka i 10 min. Tag upp dillkronorna och låt dem och lagen kallna var för sig. Varva kräftor och dillkronor i en stor skål och häll på den kalla lagen. Täck med folie och låt stå minst 1 dygn.",
    ingredients: [
      { ingredient: "Vatten", amount: "2½", unit: "l" },
      { ingredient: "Grovt salt (utan jod)", amount: "½", unit: "dl" },
      { ingredient: "Sockerbitar", amount: "2", unit: "st" },
      { ingredient: "Dillkronor", amount: "1", unit: "stor bunt" },
      { ingredient: "Porter", amount: "33", unit: "cl" },
    ],
  },
  {
    title: "Ninnis Super Crunch",
    category: "Övrigt",
    description: null,
    servings: null,
    instructions: "1. Skölj bovetet noga. Hacka nötter grovt och blanda med torra ingredienser. Lös honung i vatten, blanda med rapsolja. Häll över och knåda in.\n2. Fördela på plåt. Rosta 175° i 30 min, sänk till 150° tills allt är crunchy. Rör om var femte minut.\n3. Låt svalna. Förvara i burk med lock.",
    ingredients: [
      { ingredient: "Havregryn", amount: "3", unit: "dl" },
      { ingredient: "Bovetegryn", amount: "3", unit: "dl" },
      { ingredient: "Nötter (cashew, mandel, valnötter)", amount: "7", unit: "dl" },
      { ingredient: "Solrosfrön eller pumpafrön", amount: "1", unit: "dl" },
      { ingredient: "Sesamfrön", amount: "1", unit: "dl" },
      { ingredient: "Chiafrön", amount: "0,5", unit: "dl" },
      { ingredient: "Riven kokos", amount: "1,5", unit: "dl" },
      { ingredient: "Kanel", amount: "4-5", unit: "msk" },
      { ingredient: "Vaniljpulver", amount: "1-2", unit: "tsk" },
      { ingredient: "Rapsolja", amount: "0,5", unit: "dl" },
      { ingredient: "Honung", amount: "1", unit: "msk" },
      { ingredient: "Vatten", amount: "1,5", unit: "dl" },
    ],
  },
  {
    title: "Stekfond",
    category: "Övrigt",
    description: null,
    servings: null,
    instructions: null,
    ingredients: [
      { ingredient: "Schalottenlök", amount: "1", unit: "st" },
      { ingredient: "Morot, rotselleri, palsternacka", amount: null, unit: "liten bit" },
      { ingredient: "Socker (råsocker)", amount: "1", unit: "msk" },
      { ingredient: "Balsamvinäger", amount: "1", unit: "msk" },
      { ingredient: "Tomatpuré", amount: "1", unit: "tsk" },
      { ingredient: "Mörk choklad 70%", amount: "1", unit: "ruta" },
      { ingredient: "Mörk oxfond buljongtärning", amount: "1", unit: "st" },
      { ingredient: "Köttbuljongtärning", amount: "½", unit: "st" },
      { ingredient: "Bongs rödvinsfond", amount: null, unit: null },
      { ingredient: "Smör", amount: "100-150", unit: "g" },
    ],
  },
];

// ── Main ─────────────────────────────────────────────────────
async function main() {
  const familyId = process.argv[2];

  if (!familyId) {
    console.log("Användning: node supabase/seed.mjs <family_id>\n");
    console.log("Tillgängliga familjer:");
    const families = await listFamilies();
    if (families.length === 0) {
      console.log("  (inga familjer – registrera dig först i appen)");
    } else {
      for (const f of families) {
        console.log(`  ${f.id}  ${f.name}`);
      }
    }
    process.exit(0);
  }

  console.log(`Seedar ${recipes.length} recept till familj ${familyId}…\n`);

  let ok = 0;
  let fail = 0;

  for (const r of recipes) {
    try {
      const [inserted] = await api("recipes", {
        family_id: familyId,
        title: r.title,
        description: r.description,
        instructions: r.instructions,
        category: r.category,
        source: "Familjen Frosts Kokbok",
        servings: r.servings,
        is_active: true,
      });

      if (r.ingredients.length > 0) {
        await api(
          "recipe_ingredients",
          r.ingredients.map((ing, i) => ({
            recipe_id: inserted.id,
            ingredient: ing.ingredient,
            amount: ing.amount,
            unit: ing.unit,
            sort_order: i,
          })),
        );
      }

      console.log(`  ✓ ${r.title}`);
      ok++;
    } catch (e) {
      console.error(`  ✗ ${r.title}: ${e.message}`);
      fail++;
    }
  }

  console.log(`\nKlart! ${ok} lyckades, ${fail} misslyckades.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
