#!/usr/bin/env node
/**
 * Seed script for the ~69 MISSING recipes from Familjen Frosts Kokbok.
 * Usage: node supabase/seed-missing.mjs <family_id>
 */

const SUPABASE_URL = "https://znpjchdmshvdzmwjfbfw.supabase.co";
const SERVICE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpucGpjaGRtc2h2ZHptd2pmYmZ3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTgzODkyOCwiZXhwIjoyMDkxNDE0OTI4fQ.5WPMhDRUXebeGYfwGG84L6GIi9GS4CWyEczbuJK4_4I";

const headers = {
  apikey: SERVICE_KEY,
  Authorization: `Bearer ${SERVICE_KEY}`,
  "Content-Type": "application/json",
  Prefer: "return=representation",
};

async function api(path, body) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
    method: "POST",
    headers,
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`${res.status} ${path}: ${text}`);
  }
  return res.json();
}

async function listFamilies() {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/families?select=id,name`, { headers });
  return res.json();
}

async function getExistingTitles(familyId) {
  const res = await fetch(
    `${SUPABASE_URL}/rest/v1/recipes?select=title&family_id=eq.${familyId}`,
    { headers },
  );
  const data = await res.json();
  return new Set(data.map((r) => r.title.toLowerCase().trim()));
}

const recipes = [
  // ═══ HUVUDRÄTTER ═══
  {
    title: "Alex's club Sandwich",
    category: "Huvudrätter",
    description: null,
    servings: 2,
    instructions:
      "1. Grilla kycklingfilén och skär i tunna skivor. Knaperstek baconet i hela skivor och låt rinna av på papper.\n2. Blanda crème fraiche, majonnäs, tomatfond, parmesan, socker, salt och peppar till en dressing.\n3. Stek brödet i rikligt med smör och provençalsk krydda samt lite salt tills det är gyllenbrunt på båda sidor.\n4. Montera: bröd, kyckling, dressing, sallad, ev bröd, tomat, bacon, dressing och bröd. Servera genast.",
    ingredients: [
      { ingredient: "Kycklingfilé", amount: "1", unit: "st" },
      { ingredient: "Bacon", amount: "1", unit: "pkt" },
      { ingredient: "Tomat i tunna skivor", amount: "1", unit: "st" },
      { ingredient: "Isbergssallad, strimlad", amount: null, unit: null },
      { ingredient: "Formfranska", amount: "4-6", unit: "skivor" },
      { ingredient: "Crème fraiche", amount: "1", unit: "dl" },
      { ingredient: "Majonnäs", amount: "1", unit: "msk" },
      { ingredient: "Tomatfond", amount: "4", unit: "msk" },
      { ingredient: "Finriven parmesan", amount: "1", unit: "dl" },
      { ingredient: "Socker", amount: "1", unit: "nypa" },
      { ingredient: "Smör", amount: null, unit: null },
      { ingredient: "Provençalsk krydda", amount: null, unit: null },
    ],
  },
  {
    title: "Allt i allo gryta",
    category: "Huvudrätter",
    description: null,
    servings: 8,
    instructions:
      "1. Bryn nötköttet, bacon i bitar och hackad gul lök separat. Häll på vin, vatten och buljong i en gryta med köttet, bacon, den gula löken, vitlök, lagerblad, timjan, peppar och tomatpuré. Koka grytan i 1 timme med lock.\n2. Om köttet känns mört, tillsätt hackad palsternacka, morot, lök, champinjoner och potatis. Koka ½ timme. Smaka av med grädde och/eller crème fraiche samt ev. färsk timjan.",
    ingredients: [
      { ingredient: "Nötkött i stora bitar", amount: "1,5", unit: "kg" },
      { ingredient: "Bacon", amount: "2", unit: "pkt" },
      { ingredient: "Gula lökar", amount: "2", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "10", unit: "st" },
      { ingredient: "Lagerblad", amount: "2", unit: "st" },
      { ingredient: "Timjan", amount: null, unit: null },
      { ingredient: "Krossad grönpeppar", amount: "½", unit: "tsk" },
      { ingredient: "Palsternackor", amount: "4", unit: "st" },
      { ingredient: "Morötter", amount: "4", unit: "st" },
      { ingredient: "Rött vin", amount: "3", unit: "dl" },
      { ingredient: "Vatten", amount: "1,3", unit: "liter" },
      { ingredient: "Grädde eller crème fraiche", amount: "1-2", unit: "dl" },
      { ingredient: "Tomatpuré", amount: "1", unit: "msk" },
      { ingredient: "Köttbuljong", amount: "1", unit: "tärning" },
      { ingredient: "Mörk oxfond", amount: "2-3", unit: "tärningar" },
      { ingredient: "Små champinjoner", amount: "300", unit: "g" },
    ],
  },
  {
    title: "Basilikagnudi med broccoli",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions:
      "1. Gnudi: Finhacka basilikan. Lägg i en bunke med ricotta, ägg, mjöl, parmesan och salt. Rör ihop väl. Spritsa ut valnötsstora klickar av smeten på polentagryn, eller forma med två skedar. Låt vila 10 min.\n2. Skär broccolin i små buketter. Skiva chili och vitlök tunt.\n3. Fräs broccolin i smör på medelvärme. Höj värmen så smöret blir brunt och nötigt. Dra från värmen, tillsätt chili och vitlök.\n4. Sjud gnudin i välsaltat vatten tills de flyter upp. Ta upp och låt rinna av.\n5. Servera gnudin varm med broccolin och extra parmesan.",
    ingredients: [
      { ingredient: "Broccoli", amount: "250", unit: "g" },
      { ingredient: "Chili", amount: "½", unit: "st" },
      { ingredient: "Vitlöksklyfta", amount: "1", unit: "st" },
      { ingredient: "Smör", amount: "25", unit: "g" },
      { ingredient: "Polentagryn", amount: null, unit: null },
      { ingredient: "Basilika", amount: "1", unit: "kruka" },
      { ingredient: "Ricottaost", amount: "250", unit: "g" },
      { ingredient: "Ägg", amount: "2", unit: "st" },
      { ingredient: "Vetemjöl", amount: "1½", unit: "dl" },
      { ingredient: "Riven parmesanost", amount: "4", unit: "dl" },
      { ingredient: "Salt", amount: "2", unit: "krm" },
    ],
  },
  {
    title: "Biffwok i soja",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "Marinera köttet i soja, salt och vitpeppar minst 30 min.\n1. Woka köttet i rapsolja och smör, lite i taget. Tag ur pannan. Woka löken tills den fått färg, tillsätt chili, vitlök och fortsätt steka. Tag ur.\n2. Woka vitkål och morot några minuter i het wok med mycket olja. Tillsätt broccoli och bambuskott, woka lite till. Tillsätt paprikor och ev svamp.\n3. Häll i ca 3 dl vatten, kinesisk soja, salt, svartpeppar och lite socker. Lägg i köttbuljongen. Hetta upp och servera.",
    ingredients: [
      { ingredient: "Tunt skuren biff i strimlor", amount: "500", unit: "g" },
      { ingredient: "Japansk soja", amount: "1", unit: "msk" },
      { ingredient: "Salt", amount: "½", unit: "tsk" },
      { ingredient: "Olja", amount: "2", unit: "msk" },
      { ingredient: "Bambuskott", amount: "1", unit: "burk" },
      { ingredient: "Gul lök", amount: "1", unit: "st" },
      { ingredient: "Röda chilis", amount: "2-3", unit: "st" },
      { ingredient: "Kinesisk mushroom soy", amount: null, unit: "msk" },
      { ingredient: "Köttbuljongtärning", amount: "½", unit: "st" },
      { ingredient: "Socker", amount: "½", unit: "msk" },
      { ingredient: "Vitkål", amount: "1", unit: "klyfta" },
      { ingredient: "Vitlöksklyfta", amount: "1", unit: "st" },
      { ingredient: "Broccoli", amount: "1", unit: "näve" },
      { ingredient: "Morot", amount: "1", unit: "st" },
      { ingredient: "Paprika", amount: "1-2", unit: "st" },
    ],
  },
  {
    title: "Broccoli och kasslergratäng",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "Koka broccolibuketter 3-4 min. Spola av med kallt vatten. Koka pastaskruvarna mjuka. Koka upp grädde, matlagningsgrädde, mjölk och riven ost. Sjud under omrörning tills osten smält. Red något. Lägg i salt, svartpeppar och muskot. Lägg kasslerskivor, broccoli och pasta i gratängform. Häll över ostsåsen. Lägg ev ost överst. Gratinera 225°C i 15 min.",
    ingredients: [
      { ingredient: "Broccolibuketter", amount: null, unit: null },
      { ingredient: "Pastaskruvar", amount: null, unit: null },
      { ingredient: "Grädde", amount: "3", unit: "dl" },
      { ingredient: "Matlagningsgrädde", amount: "3", unit: "dl" },
      { ingredient: "Mjölk", amount: "3", unit: "dl" },
      { ingredient: "Riven ost", amount: "2-3", unit: "dl" },
      { ingredient: "Kasslerskivor", amount: null, unit: null },
      { ingredient: "Muskot", amount: null, unit: null },
      { ingredient: "Salt och peppar", amount: null, unit: null },
    ],
  },
  {
    title: "Broccolitimbal",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "Ansa broccolin och koka mjuk. Mixa ägg, grädde och broccoli till en smet. Smaka av med salt och peppar. Smörj portionsformar och häll i smeten. Baka i vattenbad i 200°C ugn i ca 20-30 min tills timbalen blir fast och får lite färg.",
    ingredients: [
      { ingredient: "Broccoli", amount: "250", unit: "g" },
      { ingredient: "Ägg", amount: "3", unit: "st" },
      { ingredient: "Vispgrädde", amount: "1-1½", unit: "dl" },
      { ingredient: "Salt", amount: null, unit: null },
      { ingredient: "Peppar", amount: null, unit: null },
    ],
  },
  {
    title: "Coq au vin kycklinggryta",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "Stek kycklingfilén i bitar och ställ åt sidan. Stek bacon och ställ åt sidan. Stek den gula löken i baconfettet i en gryta. Häll i morot, palsternacka, rotselleri, fänkål, tomat, buljong, vin, vatten så det täcker grönsakerna. Koka i 15 min med örtkryddor. Tillsätt allt övrigt och koka ytterligare ca 10 min.",
    ingredients: [
      { ingredient: "Kycklingfilé", amount: "1", unit: "kg" },
      { ingredient: "Gula lökar, hackade", amount: "2", unit: "st" },
      { ingredient: "Zucchini i bitar", amount: "1", unit: "st" },
      { ingredient: "Gul paprika", amount: "1", unit: "st" },
      { ingredient: "Rotselleri", amount: "1", unit: "bit" },
      { ingredient: "Fänkål", amount: "1", unit: "st" },
      { ingredient: "Morötter", amount: "5", unit: "st" },
      { ingredient: "Palsternackor", amount: "2", unit: "st" },
      { ingredient: "Burk tomater", amount: "1", unit: "burk" },
      { ingredient: "Purjolök", amount: "½", unit: "st" },
      { ingredient: "Bacon", amount: "1", unit: "pkt" },
      { ingredient: "Vin (vitt eller rött)", amount: "3", unit: "dl" },
      { ingredient: "Örtkrydda (timjan/provençalsk)", amount: null, unit: null },
      { ingredient: "Hönsbuljongtärningar", amount: "3-4", unit: "st" },
      { ingredient: "Crème fraiche", amount: "1", unit: "burk" },
      { ingredient: "Grädde", amount: "2", unit: "dl" },
    ],
  },
  {
    title: "Couscoussallad med rostade grönsaker och het sås",
    category: "Huvudrätter",
    description: null,
    servings: 10,
    instructions:
      "Dela grönsakerna i lagom bitar. Fördela på ugnsplåtar med hackad vitlök, basilika, salt och olivolja. Rosta i 250°C i 25-30 min. Koka couscous i saltat vatten, rör med gaffel. Blanda dressing av olivolja, limesaft, tomatpuré, spiskummin, cayennepeppar och salt. Blanda grönsaker och couscous, servera med isbergssallad och dressing.",
    ingredients: [
      { ingredient: "Tomater (gärna körsbär)", amount: "800", unit: "g" },
      { ingredient: "Squash (grön och gul)", amount: "800", unit: "g" },
      { ingredient: "Små paprikor", amount: "5", unit: "st" },
      { ingredient: "Fänkål", amount: "2", unit: "st" },
      { ingredient: "Rödlökar", amount: "2", unit: "st" },
      { ingredient: "Morötter", amount: "3", unit: "st" },
      { ingredient: "Champinjoner", amount: "300", unit: "g" },
      { ingredient: "Minimajs", amount: "1", unit: "burk" },
      { ingredient: "Vitlöksklyftor", amount: "4", unit: "st" },
      { ingredient: "Basilikablad", amount: "1½", unit: "dl" },
      { ingredient: "Couscousgryn", amount: "6", unit: "dl" },
      { ingredient: "Olivolja (dressing)", amount: "2", unit: "dl" },
      { ingredient: "Lime- eller citronsaft", amount: "1", unit: "dl" },
      { ingredient: "Tomatpuré", amount: "4", unit: "msk" },
      { ingredient: "Spiskummin", amount: "4", unit: "msk" },
      { ingredient: "Cayennepeppar", amount: "1-2", unit: "tsk" },
    ],
  },
  {
    title: "Den bästa vegetariska lasagnen",
    category: "Huvudrätter",
    description: null,
    servings: 6,
    instructions:
      "1. Skala morötterna och skär i stavar, zucchinin i bitar. Hacka lök, vitlök och chili. Fräs lök, vitlök och chili i olja.\n2. Tillsätt tomatkross, grädde, morötter, zucchini, salt, socker och peppar. Puttra 10 min. Tillsätt basilika.\n3. Varva röd sås, tinad spenat, smulad fetaost och lasagneplattor i ugnsform.\n4. Toppa med riven ost. Gratinera 225°C i 25 min. Servera med ruccolasallad.",
    ingredients: [
      { ingredient: "Morötter", amount: "2", unit: "st" },
      { ingredient: "Zucchini", amount: "2", unit: "st" },
      { ingredient: "Gula lökar", amount: "2", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "2", unit: "st" },
      { ingredient: "Röd chili", amount: "1", unit: "st" },
      { ingredient: "Olja", amount: "1", unit: "msk" },
      { ingredient: "Krossade tomater", amount: "400", unit: "g" },
      { ingredient: "Vispgrädde", amount: "1", unit: "dl" },
      { ingredient: "Basilika", amount: "½", unit: "kruka" },
      { ingredient: "Fryst bladspenat", amount: "250", unit: "g" },
      { ingredient: "Fetaost", amount: "200", unit: "g" },
      { ingredient: "Lasagneplattor", amount: "8-10", unit: "st" },
      { ingredient: "Riven ost", amount: "150", unit: "g" },
    ],
  },
  {
    title: "Fish tacos",
    category: "Huvudrätter",
    description: "Rätt med viss sötma och hetta från chili.",
    servings: null,
    instructions:
      "1. Hyvla sparris och morötter och lägg i isvatten.\n2. Blanda majonnäs med ingefära och chilisås. Marinera laxen i soja, chiliflakes och limesaft.\n3. Fritera tortillabröden i olja 160°C, vik på mitten.\n4. Blanda sparris och morötter med limesaft, sesamolja och soja. Skiva laxen tunt och täck med sesamfrön.\n5. Fyll brödet med grönsaker, lax, koriander och majonnäs.",
    ingredients: [
      { ingredient: "Små tortillabröd", amount: "8", unit: "st" },
      { ingredient: "Salmalax", amount: "400", unit: "g" },
      { ingredient: "Grön sparris", amount: "100", unit: "g" },
      { ingredient: "Små morötter", amount: "2", unit: "st" },
      { ingredient: "Majonnäs", amount: "1", unit: "dl" },
      { ingredient: "Riven ingefära", amount: "1", unit: "msk" },
      { ingredient: "Chilisås", amount: "1", unit: "tsk" },
      { ingredient: "Lime", amount: "1", unit: "st" },
      { ingredient: "Koriander", amount: "½", unit: "kruka" },
      { ingredient: "Japansk soja", amount: "1", unit: "dl" },
      { ingredient: "Chiliflakes", amount: "1", unit: "tsk" },
      { ingredient: "Sesamolja", amount: "1", unit: "msk" },
      { ingredient: "Rostade sesamfrön", amount: "2", unit: "msk" },
    ],
  },
  {
    title: "Fläskfilé med pesto",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions:
      "1. Ugn 200°C. Tina spenaten, krama ur vattnet. Strimla soltorkade tomater, hacka löken. Blanda spenat, tomater och lök med vitlök, olivolja, citronjuice, salt och peppar.\n2. Olja folieark och fördela spenatblandningen.\n3. Dela fläskfilén i 4, skär grova skåror. Krydda med salt och peppar. Lägg på grönsakerna.\n4. Skeda över pesto i skårorna. Vik ihop paketen. Grädda 20 min.\n5. Servera med pasta eller potatisgratäng.",
    ingredients: [
      { ingredient: "Fläskfilé", amount: "500", unit: "g" },
      { ingredient: "Fryst bladspenat", amount: "250", unit: "g" },
      { ingredient: "Soltorkade tomater", amount: "4-6", unit: "st" },
      { ingredient: "Gul lök", amount: "½", unit: "st" },
      { ingredient: "Vitlöksklyfta", amount: "1", unit: "st" },
      { ingredient: "Olivolja", amount: "1", unit: "msk" },
      { ingredient: "Citronjuice", amount: "1", unit: "msk" },
      { ingredient: "Pesto", amount: "200", unit: "g" },
      { ingredient: "Pasta", amount: "4-8", unit: "port" },
      { ingredient: "Ugnsfolie", amount: "4", unit: "ark" },
    ],
  },
  {
    title: "Förälskade havskräftor",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions:
      "1. Koka ihop hummersoppan ca 10 min.\n2. Häll olja i pannan och fräs löken blank. Blanda i champinjoner och hackade örter. Lägg i kräftstjärtarna och rör om.\n3. Häll i spriten och tänd på (försiktigt!). Obs: köksfläkten måste vara avstängd.\n4. När lågan slocknat, tillsätt grädden uppvispad till krämkonsistens. Tillsätt hummersoppan. Låt hastigt koka ihop till tjock sås.\n5. Ta från värmen och rör ner hollandaisesås. Servera med ris.",
    ingredients: [
      { ingredient: "Råa havskräftstjärtar", amount: "4-6", unit: "st/person" },
      { ingredient: "Rapsolja", amount: "3", unit: "msk" },
      { ingredient: "Finhackad schalottenlök", amount: "2", unit: "msk" },
      { ingredient: "Champinjoner, skivade", amount: "300", unit: "g" },
      { ingredient: "Persilja/dragon/körvel", amount: "4", unit: "msk" },
      { ingredient: "Konjak", amount: "3", unit: "cl" },
      { ingredient: "Pernod", amount: "3", unit: "cl" },
      { ingredient: "Vispgrädde", amount: "2", unit: "dl" },
      { ingredient: "Hollandaisesås", amount: "5-8", unit: "msk" },
      { ingredient: "Fransk hummersoppa", amount: "1", unit: "burk" },
    ],
  },
  {
    title: "Gratinerad hummer",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions:
      "Dela humrarna på längden och ta ur köttet. Hacka i mindre bitar och blanda med majonnäs, ost och cognac. Smaka av med salt och cayennepeppar. Lägg massan i skalhalvorna. Gratinera 250°C i 5-10 min tills fin färg. Servera med torrt vitt mousserande vin.",
    ingredients: [
      { ingredient: "Humrar", amount: "2", unit: "st" },
      { ingredient: "Äkta majonnäs", amount: "1", unit: "dl" },
      { ingredient: "Riven emmentaler", amount: "1½-2", unit: "dl" },
      { ingredient: "Cognac", amount: "1-2", unit: "msk" },
      { ingredient: "Salt", amount: null, unit: null },
      { ingredient: "Cayennepeppar", amount: "1", unit: "knivsudd" },
    ],
  },
  {
    title: "Gratinerade sniglar",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions:
      "Ugn 275°C. Skölj av sniglarna. Rör ihop vitlökssmöret av smör, krossad vitlök, finhackad schalottenlök, citronsaft, persilja och salt. Lägg sniglarna i snigeltallrikar. Strö ströbröd över. Lägg i en klick vitlökssmör per fördjupning. Gratinera 5-10 min tills smöret kokar men inte brunnar. Servera med vitt vin och bröd.",
    ingredients: [
      { ingredient: "Sniglar på burk", amount: "4", unit: "dussin" },
      { ingredient: "Smör", amount: "200", unit: "g" },
      { ingredient: "Krossade vitlöksklyftor", amount: "3-4", unit: "st" },
      { ingredient: "Finhackad schalottenlök", amount: "1", unit: "st" },
      { ingredient: "Citronsaft", amount: "2", unit: "tsk" },
      { ingredient: "Persilja", amount: null, unit: "msk" },
      { ingredient: "Salt", amount: null, unit: null },
      { ingredient: "Ströbröd", amount: null, unit: null },
    ],
  },
  {
    title: "Hoisinkyckling",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions:
      "Ugn 200°C. Skär paprika och chili, skiva löken. Blanda böngroddar, lök, chili och paprika med hoisinsås, salt och peppar. Skär skåror i kycklingfiléerna. Olja folieark, fördela grönsaker, lägg på filé och resten av blandningen. Vik ihop paket. Baka 30 min. Koka nudlar. Servera med extra hoisinsås.",
    ingredients: [
      { ingredient: "Kycklingfiléer", amount: "4", unit: "st" },
      { ingredient: "Röd paprika", amount: "1", unit: "st" },
      { ingredient: "Röd chili", amount: "½-1", unit: "st" },
      { ingredient: "Gul lök", amount: "1", unit: "st" },
      { ingredient: "Böngroddar", amount: "400", unit: "g" },
      { ingredient: "Hoisinsås", amount: "1", unit: "dl" },
      { ingredient: "Asiatiska äggnudlar", amount: "200", unit: "g" },
      { ingredient: "Ugnsfolie", amount: "4", unit: "ark" },
    ],
  },
  {
    title: "Japansk fondue",
    category: "Huvudrätter",
    description: null,
    servings: 6,
    instructions:
      "Buljong: Skala och skiva ingefäran. Koka alla ingredienser till buljongen i 15 min, sila av ingefäran. Stek kött och svamp. Servera med morötter i stavar, blomkål, sockerärtor/salladsbönor, cashewnötter, glasnudlar och färsk kål.",
    ingredients: [
      { ingredient: "Ingefära", amount: "10", unit: "cm" },
      { ingredient: "Vatten", amount: "2", unit: "liter" },
      { ingredient: "Kalvbuljong", amount: "¾", unit: "dl" },
      { ingredient: "Japansk soja", amount: "1", unit: "dl" },
      { ingredient: "Mirin", amount: "1", unit: "msk" },
      { ingredient: "Salt", amount: "1½", unit: "krm" },
    ],
  },
  {
    title: "Kong Pao Kyckling",
    category: "Huvudrätter",
    description: "Mycket smakrik med smaker av sött, surt, chili och Sichuan-peppar.",
    servings: 2,
    instructions:
      "1. Skär kött och paprikor i tärningar. Marinera köttet med salt, kycklingbuljong, maizena och halva sojan i 10 min.\n2. Skär ingefära och vitlök i tunna skivor, vårlöken i stavar. Stek köttet i het olja, lägg åt sidan.\n3. Ny olja, stek torkad chili, Sichuan-peppar, ingefära, vitlök och vårlök. Lägg i kycklingen, stänk cherryn.\n4. Blanda socker, vinäger, soja, maizena med vatten och buljong. Häll över köttet, strö cashewnötter och blanda ihop.",
    ingredients: [
      { ingredient: "Kycklinglår utan ben", amount: "250", unit: "g" },
      { ingredient: "Röd paprika", amount: "50", unit: "g" },
      { ingredient: "Grön paprika", amount: "50", unit: "g" },
      { ingredient: "Cashewnötter, osaltade", amount: "100", unit: "g" },
      { ingredient: "Ingefära", amount: "1,5", unit: "cm" },
      { ingredient: "Vitlöksklyfta", amount: "1", unit: "st" },
      { ingredient: "Kinesisk vårlök", amount: "2", unit: "st" },
      { ingredient: "Torkad chili", amount: "6", unit: "st" },
      { ingredient: "Sichuan-pepparkorn", amount: "16", unit: "st" },
      { ingredient: "Mörk soja", amount: "1", unit: "msk" },
      { ingredient: "Svart risvinäger", amount: "1,5", unit: "msk" },
      { ingredient: "Maizena", amount: "1", unit: "msk" },
      { ingredient: "Socker", amount: "1", unit: "msk" },
      { ingredient: "Jordnötsolja", amount: "10", unit: "msk" },
    ],
  },
  {
    title: "Kyckling med getost",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "Stek kycklingfiléerna i smör i gjutjärnspanna. Lägg i ugnsform. Vispa ur stekpannan med vatten och lös upp buljong. Häll stekspadet över kycklingen. Salta, peppra, krydda med paprikapulver och cayennepeppar. Strö över hackade soltorkade tomater och basilikablad. Häll över grädden. Lägg på getost i tunna skivor. Tryck ner kycklingen. Gratinera 225°C i 30 min.",
    ingredients: [
      { ingredient: "Kycklingfiléer", amount: "5", unit: "st" },
      { ingredient: "Soltorkade tomater", amount: "10", unit: "st" },
      { ingredient: "Getost (rulle)", amount: "1", unit: "st" },
      { ingredient: "Grädde", amount: "4", unit: "dl" },
      { ingredient: "Hönsbuljongtärning", amount: "1", unit: "st" },
      { ingredient: "Basilika", amount: "1", unit: "kruka" },
      { ingredient: "Cayennepeppar", amount: null, unit: null },
      { ingredient: "Paprikapulver", amount: null, unit: null },
      { ingredient: "Smör", amount: null, unit: null },
    ],
  },
  {
    title: "Kycklingkebab",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "1. Marinera kvällen innan: blanda vitlök, olivolja, chiliflingor, koriander, kanel, paprika, oregano, salt, citronsaft och lökpulver. Gnid in marinaden i urbenade kycklinglår. Kylskåp minst 4 timmar.\n2. Ugn 200°C. Trä kyckling på metallspett. Grilla 45 min, vänd så det grillas jämnt.\n3. Dillmajonnäs: blanda yoghurt, majonnäs och dill.\n4. Servera i pitabröd med sallad, rödlök och tomat.",
    ingredients: [
      { ingredient: "Kycklinglår, urbenade", amount: "6", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "2", unit: "st" },
      { ingredient: "Olivolja", amount: "3", unit: "msk" },
      { ingredient: "Chiliflingor", amount: "½", unit: "tsk" },
      { ingredient: "Koriander", amount: "½", unit: "tsk" },
      { ingredient: "Kanel", amount: "½", unit: "tsk" },
      { ingredient: "Paprika", amount: "1", unit: "tsk" },
      { ingredient: "Oregano", amount: "1", unit: "tsk" },
      { ingredient: "Citron", amount: "½", unit: "st" },
      { ingredient: "Grekisk yoghurt", amount: "4½", unit: "msk" },
      { ingredient: "Majonnäs", amount: "3", unit: "msk" },
      { ingredient: "Dill", amount: "1½", unit: "msk" },
      { ingredient: "Pitabröd", amount: "4", unit: "st" },
    ],
  },
  {
    title: "Krämiga nudlar med röd curry och krispig fräs",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions:
      "1. Fräs currypasten i olja 1 min. Tillsätt kokosmjölk, koka ihop 5 min. Smaka av.\n2. Fräs färsen med vitlök, ingefära, soja och socker.\n3. Koka pak choi 1 min. Koka nudlar enligt förpackning. Rör ner nudlar i såsen.\n4. Toppa med färs, pak choi, salladslök och sesamfrön. Servera med lime.",
    ingredients: [
      { ingredient: "Röd currypasta", amount: "2", unit: "msk" },
      { ingredient: "Kokosmjölk", amount: "400", unit: "ml" },
      { ingredient: "Vego- eller fläskfärs", amount: "400", unit: "g" },
      { ingredient: "Riven vitlöksklyfta", amount: "1", unit: "st" },
      { ingredient: "Riven ingefära", amount: "2", unit: "msk" },
      { ingredient: "Japansk soja", amount: "2-3", unit: "msk" },
      { ingredient: "Socker", amount: "1", unit: "msk" },
      { ingredient: "Pak choi", amount: "250", unit: "g" },
      { ingredient: "Nudlar", amount: "200", unit: "g" },
      { ingredient: "Salladslökar", amount: "3", unit: "st" },
      { ingredient: "Rostade sesamfrön", amount: "2", unit: "msk" },
    ],
  },
  {
    title: "Kycklinggryta med grov senap och dragon",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "1. Grovstycka kycklingen. Hacka vitlök, skär champinjoner i fjärdedelar. Bryn kycklingen i olja med vitlök.\n2. Bryn svampen separat. Lägg allt i kastrull med fond, vatten och grädde. Koka sakta 30-40 min.\n3. Smaka av med senap, salt och peppar. Red med majsstärkelse. Vänd ner dragon och vinäger.",
    ingredients: [
      { ingredient: "Hel färsk kyckling", amount: "1", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "2", unit: "st" },
      { ingredient: "Champinjoner", amount: "250", unit: "g" },
      { ingredient: "Olja", amount: "1", unit: "msk" },
      { ingredient: "Kycklingfond", amount: "2", unit: "msk" },
      { ingredient: "Vatten", amount: "2", unit: "dl" },
      { ingredient: "Grädde", amount: "2½", unit: "dl" },
      { ingredient: "Grov senap", amount: "2½", unit: "msk" },
      { ingredient: "Majsstärkelse", amount: "1", unit: "msk" },
      { ingredient: "Färsk dragon", amount: "1", unit: "msk" },
      { ingredient: "Vit balsamvinäger", amount: "1", unit: "msk" },
    ],
  },
  {
    title: "Lamm med pistage och harissa-morötter",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "1. Tahini-yoghurtsås: blanda yoghurt, citronskal, citronsaft, vitlök, tahini och mynta.\n2. Putsa lammfilén. Mal spiskummin, korianderfrön och svartpeppar. Gnid in kryddor, stek på hög värme. Pensla med äggvita, rulla i pistagenötskross. Stek klart i ugn 140°C till 59°C innertemp. Vila 5 min.\n3. Harissa-morötter: rosta spiskummin i olivolja, tillsätt kardemumma och harissa. Lägg i morötter, lönnsirap och citronsaft. Koka tills mjuka med spänstig kärna.\n4. Servera med mynta och granatäppelkärnor.",
    ingredients: [
      { ingredient: "Lammytterfilé", amount: "300", unit: "g" },
      { ingredient: "Spiskummin", amount: "1", unit: "msk" },
      { ingredient: "Korianderfrön", amount: "2", unit: "tsk" },
      { ingredient: "Pistagenötter", amount: "2", unit: "dl" },
      { ingredient: "Äggvita", amount: "1", unit: "st" },
      { ingredient: "Knippmorötter", amount: "10", unit: "st" },
      { ingredient: "Harissa", amount: "2", unit: "msk" },
      { ingredient: "Lönnsirap", amount: "4", unit: "msk" },
      { ingredient: "Turkisk yoghurt", amount: "2", unit: "dl" },
      { ingredient: "Tahini", amount: "3", unit: "msk" },
      { ingredient: "Mynta", amount: "1", unit: "kruka" },
      { ingredient: "Citron", amount: "1", unit: "st" },
    ],
  },
  {
    title: "Langos med tomater, mozzarella och pesto",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "1. Koka och mosa potatis. Blanda ut jästen i fingervarmt vatten. Tillsätt salt, mjöl och potatis, arbeta till deg. Jäs 1 timme.\n2. Dela i 12 bitar, forma bullar, platta ut och skär jack. Jäs 20 min.\n3. Fritera i olja 180°C ca 2 min tills gyllenbruna.\n4. Lägg ut tomater och mozzarella på brödet, toppa med pesto och sallad.",
    ingredients: [
      { ingredient: "Vatten", amount: "4", unit: "dl" },
      { ingredient: "Potatisar", amount: "2", unit: "st" },
      { ingredient: "Jäst", amount: "¼", unit: "pkt" },
      { ingredient: "Salt", amount: "1", unit: "msk" },
      { ingredient: "Vetemjöl", amount: "8-9", unit: "dl" },
      { ingredient: "Neutral matolja", amount: "1", unit: "liter" },
      { ingredient: "Mozzarella", amount: "400", unit: "g" },
      { ingredient: "Tomater", amount: null, unit: null },
      { ingredient: "Pesto", amount: null, unit: null },
    ],
  },
  {
    title: "Lasagne med köttfärs",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions: null,
    ingredients: [
      { ingredient: "Nötfärs eller köttfärs", amount: "800", unit: "g" },
      { ingredient: "Hela tomater", amount: "3", unit: "burkar" },
      { ingredient: "Oregano", amount: null, unit: "tsk" },
      { ingredient: "Vitlöksklyfta, hackad", amount: "1", unit: "st" },
      { ingredient: "Gula lökar, hackade", amount: "2", unit: "st" },
      { ingredient: "Zucchini, hackad", amount: "1", unit: "st" },
      { ingredient: "Morötter, rivna", amount: "4", unit: "st" },
      { ingredient: "Köttbuljong", amount: "2", unit: "tärningar" },
      { ingredient: "Olivolja", amount: null, unit: null },
    ],
  },
  {
    title: "Lax på rotfruktsbädd",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "Strimla grönsakerna. Koka 1 dl grönsaksbuljong i 5 min tills vätskan kokat in. Blanda vatten, vin och mjöl med buljongtärning. Koka 5 min. Rör ihop grädde och äggula och rör i. Koka ej såsen efter detta. Ångkoka laxen. Servera på rotfrukterna med såsen.",
    ingredients: [
      { ingredient: "Laxbitar", amount: "4", unit: "st" },
      { ingredient: "Morötter", amount: "2", unit: "st" },
      { ingredient: "Rotselleri", amount: "200", unit: "g" },
      { ingredient: "Palsternacka", amount: "1", unit: "st" },
      { ingredient: "Purjolök", amount: "1", unit: "st" },
      { ingredient: "Vatten", amount: "1", unit: "dl" },
      { ingredient: "Vitt vin", amount: "1", unit: "dl" },
      { ingredient: "Vetemjöl", amount: "1½", unit: "msk" },
      { ingredient: "Fiskbuljongtärning", amount: "1", unit: "st" },
      { ingredient: "Matlagningsgrädde", amount: "1", unit: "dl" },
      { ingredient: "Äggula", amount: "1", unit: "st" },
    ],
  },
  {
    title: "Pad thai",
    category: "Huvudrätter",
    description: null,
    servings: 8,
    instructions: null,
    ingredients: [
      { ingredient: "Glasnudlar", amount: "500", unit: "g" },
      { ingredient: "Vitlöksklyftor", amount: "4", unit: "st" },
      { ingredient: "Röda chilis", amount: "3", unit: "st" },
      { ingredient: "Morötter i tändstickor", amount: "4", unit: "st" },
      { ingredient: "Salladslök", amount: "1", unit: "påse" },
      { ingredient: "Fisksås", amount: "4", unit: "msk" },
      { ingredient: "Limejuice", amount: "2", unit: "st" },
      { ingredient: "Socker", amount: "4", unit: "msk" },
      { ingredient: "Kycklingfilé", amount: "800", unit: "g" },
      { ingredient: "Ägg", amount: "4", unit: "st" },
      { ingredient: "Blomkål, paprika, vitkål", amount: null, unit: null },
      { ingredient: "Hackade jordnötter", amount: "2", unit: "dl" },
      { ingredient: "Koriander", amount: null, unit: null },
    ],
  },
  {
    title: "Paprikaskal med guacamole",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "Baka potatisen 200°C i 1 timme. Dela i halvor, skopa ur. Dela halvorna igen, pensla med olivolja, strö paprikapulver och salt. Baka 10-15 min tills krispiga. Blanda guacamole av avokado, lime, koriander, chili och vitlök. Servera med gräddfil.",
    ingredients: [
      { ingredient: "Bakpotatis", amount: "6", unit: "st" },
      { ingredient: "Olivolja", amount: "4", unit: "tsk" },
      { ingredient: "Paprikapulver", amount: "1", unit: "tsk" },
      { ingredient: "Mogna avocado", amount: "2", unit: "st" },
      { ingredient: "Limejuice", amount: "2", unit: "st" },
      { ingredient: "Koriander", amount: "3", unit: "tsk" },
      { ingredient: "Grön chili", amount: "1", unit: "st" },
      { ingredient: "Vitlöksklyfta", amount: "1", unit: "st" },
      { ingredient: "Gräddfil", amount: "250", unit: "ml" },
      { ingredient: "Vårlökar", amount: "3", unit: "st" },
    ],
  },
  {
    title: "Pasta med kalvfrikadeller i tomatsås",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions:
      "1. Hacka lök och vitlök smått. Fräs med salvia i olja 3 min.\n2. Tillsätt tomater, socker, salt och peppar. Puttra 15 min.\n3. Blanda färs med halva osten, ägg och salt. Rulla till små bollar. Koka pasta.\n4. Sjud frikadellerna i tomatsåsen 3 min. Vänd runt pastan med sås och frikadeller. Servera med pecorinoost.",
    ingredients: [
      { ingredient: "Spaghetti/linguine", amount: "400", unit: "g" },
      { ingredient: "Gul lök", amount: "1", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "3", unit: "st" },
      { ingredient: "Färsk salvia", amount: "2", unit: "msk" },
      { ingredient: "Olivolja", amount: "½", unit: "dl" },
      { ingredient: "Passerade tomater", amount: "500", unit: "g" },
      { ingredient: "Råsocker", amount: "1", unit: "tsk" },
      { ingredient: "Kalvfärs", amount: "400", unit: "g" },
      { ingredient: "Riven pecorinoost", amount: "100", unit: "g" },
      { ingredient: "Ägg", amount: "1", unit: "st" },
    ],
  },
  {
    title: "Pasta med kronärtskocka och citron",
    category: "Huvudrätter",
    description: null,
    servings: 6,
    instructions:
      "1. Hacka vitlök och kronärtskockor. Fräs vitlöken i olja från kronärtskockorna. Tillsätt kronärtskocka och svartpeppar, fräs. Tillsätt grädde, koka ihop. Tillsätt citronskal och salt.\n2. Koka pasta al dente. Spara 2 dl pastavatten. Tillsätt pasta och vatten i såsen. Toppa med parmesan.",
    ingredients: [
      { ingredient: "Vitlöksklyftor", amount: "2", unit: "st" },
      { ingredient: "Inlagd kronärtskocka i olja", amount: "300", unit: "g" },
      { ingredient: "Svartpeppar", amount: "1", unit: "tsk" },
      { ingredient: "Vispgrädde", amount: "2", unit: "dl" },
      { ingredient: "Finrivet citronskal", amount: "2", unit: "msk" },
      { ingredient: "Pasta", amount: "400", unit: "g" },
      { ingredient: "Riven parmesan", amount: null, unit: null },
    ],
  },
  {
    title: "Pasta med rostad blomkål",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions:
      "Ugn 225°C. Skär blomkålen i skivor. Pressa citronsaft och klicka ut smör. Krossa vitlök, strö chiliflakes, salt och peppar. Rosta 20 min. Koka pasta. Riv parmesan. Mosa vitlöksklyftorna och blanda i pastan med resten av smöret, osten och citronskalet. Lägg i blomkålen försiktigt.",
    ingredients: [
      { ingredient: "Blomkålshuvud", amount: "800", unit: "g" },
      { ingredient: "Vitlöksklyftor", amount: "5", unit: "st" },
      { ingredient: "Citron", amount: "1", unit: "st" },
      { ingredient: "Smör", amount: "50", unit: "g" },
      { ingredient: "Chiliflakes", amount: "2", unit: "krm" },
      { ingredient: "Pasta", amount: "4", unit: "port" },
      { ingredient: "Parmesan", amount: "100", unit: "g" },
    ],
  },
  {
    title: "Potatiskroketter",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "1. Koka potatis mjuk, pressa genom press. Blanda med ägg, mjöl, parmesan, citronskal och salt. Låt svalna.\n2. Rulla till 30 bollar. Panera i ägg, mjöl och sist panko.\n3. Fritera i 170-180°C olja ca 1 min tills gyllene. Rinn av. Toppa med parmesan och flingsalt.",
    ingredients: [
      { ingredient: "Mjölig potatis", amount: "1", unit: "kg" },
      { ingredient: "Vetemjöl", amount: "4", unit: "dl" },
      { ingredient: "Ägg", amount: "1", unit: "st" },
      { ingredient: "Riven parmesan", amount: "2", unit: "dl" },
      { ingredient: "Finrivet citronskal", amount: "1", unit: "msk" },
      { ingredient: "Ägg (panering)", amount: "2", unit: "st" },
      { ingredient: "Vetemjöl (panering)", amount: "2", unit: "dl" },
      { ingredient: "Panko", amount: "3", unit: "dl" },
      { ingredient: "Neutral olja", amount: "1", unit: "liter" },
    ],
  },
  {
    title: "Potatis och fänkålsgratäng",
    category: "Huvudrätter",
    description: "Gott, friskt och krispigt!",
    servings: 4,
    instructions:
      "1. Ansa och skiva fänkålen tunt. Skiva löken tunt, hacka vitlöken.\n2. Stek fänkål och lök i smör ca 20 min. Tillsätt vitlök och timjan, stek 2 min.\n3. Ugn 200°C. Skiva potatis tunt. Blanda med fänkåls-fräset, grädde, mjölk och salt. Häll i smord ugnsform. Grädda 20 min.\n4. Blanda panko och ost, strö över. Grädda 20 min till.",
    ingredients: [
      { ingredient: "Fänkål", amount: "2", unit: "st" },
      { ingredient: "Gul lök", amount: "1", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "2", unit: "st" },
      { ingredient: "Smör", amount: "3", unit: "msk" },
      { ingredient: "Timjan", amount: "2", unit: "msk" },
      { ingredient: "Fast potatis", amount: "500", unit: "g" },
      { ingredient: "Vispgrädde", amount: "4", unit: "dl" },
      { ingredient: "Mjölk", amount: "2", unit: "dl" },
      { ingredient: "Panko", amount: "2", unit: "dl" },
      { ingredient: "Riven Gruyère", amount: "2", unit: "dl" },
    ],
  },
  {
    title: "Provencalsk kycklinggryta",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "1. Bryn kycklingben i olja. Lägg i lök och vitlök.\n2. Häll i vitt vin, tomater, vatten och timjan. Koka under lock 30 min.\n3. Bryn zucchini, aubergine och paprika separat, lägg i grytan. Koka 10 min. Lägg i oliver. Smaka av med salt, peppar och socker. Avsluta med persilja.\nServera med couscous, ris eller quinoa.",
    ingredients: [
      { ingredient: "Kycklingben", amount: "900", unit: "g" },
      { ingredient: "Gul lök", amount: "½", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "3", unit: "st" },
      { ingredient: "Vitt vin", amount: "2", unit: "dl" },
      { ingredient: "Hela tomater", amount: "1", unit: "burk" },
      { ingredient: "Vatten", amount: "2", unit: "dl" },
      { ingredient: "Timjan", amount: null, unit: null },
      { ingredient: "Röd paprika", amount: "1", unit: "st" },
      { ingredient: "Grön zucchini", amount: "½", unit: "st" },
      { ingredient: "Aubergine", amount: "½", unit: "st" },
      { ingredient: "Kalamataoliver", amount: "1", unit: "dl" },
      { ingredient: "Persilja", amount: null, unit: null },
    ],
  },
  {
    title: "Ratatouillegryta med vitlöksbakad sej",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions:
      "1. Rosta vitlök i olja, mixa med bladpersilja. Salta.\n2. Snitta aubergine, salta och rosta 30 min i 200°C med olivolja och halva persiljan.\n3. Pensla resterande mix på sejen. Baka 150°C ca 8 min före servering.\n4. Fräs schalottenlök, paprika, zucchini och fänkål. Tillsätt tomater, timjan, vin och buljong. Koka 20 min. Tillsätt crème fraiche. Smaka av.\n5. Servera sej och auberginer med ratatouille och färska örter.",
    ingredients: [
      { ingredient: "Gråsej", amount: "600", unit: "g" },
      { ingredient: "Bananschalottenlökar", amount: "2", unit: "st" },
      { ingredient: "Röd paprika", amount: "1", unit: "st" },
      { ingredient: "Grön zucchini", amount: "½", unit: "st" },
      { ingredient: "Fänkål", amount: "1½", unit: "st" },
      { ingredient: "Plommontomater", amount: "2", unit: "st" },
      { ingredient: "Timjan", amount: "1", unit: "kvist" },
      { ingredient: "Vitt vin", amount: "1", unit: "dl" },
      { ingredient: "Grönsaksbuljongtärningar", amount: "1-2", unit: "st" },
      { ingredient: "Crème fraiche", amount: "1", unit: "dl" },
      { ingredient: "Vitlöksklyftor", amount: "2", unit: "st" },
      { ingredient: "Bladpersilja", amount: "1", unit: "knippe" },
      { ingredient: "Aubergine", amount: "1", unit: "st" },
    ],
  },
  {
    title: "Rispappersrullar med cashewdipp",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions:
      "Koka riset. Dipp: hacka chili, riv ingefära, mixa med cashewnötter, olja, soja, vatten och limejuice. Skär morötter, gurka, rödkål i tunna strimlor. Skiva avokado och salladslök. Vid bordet: doppa rispapper i ljummet vatten 10-15 sek, fyll med grönsaker, vik ihop. Servera med dipp.",
    ingredients: [
      { ingredient: "Ris", amount: "4", unit: "port" },
      { ingredient: "Morötter", amount: "2", unit: "st" },
      { ingredient: "Gurka", amount: "1", unit: "st" },
      { ingredient: "Rödkål", amount: "200", unit: "g" },
      { ingredient: "Avokado", amount: "2", unit: "st" },
      { ingredient: "Salladslök", amount: "125", unit: "g" },
      { ingredient: "Böngroddar", amount: "180", unit: "g" },
      { ingredient: "Koriander", amount: "1", unit: "kruka" },
      { ingredient: "Rispapper", amount: "12", unit: "ark" },
      { ingredient: "Röd chili", amount: "1", unit: "st" },
      { ingredient: "Ingefära", amount: "1", unit: "msk" },
      { ingredient: "Saltade cashewnötter", amount: "100", unit: "g" },
      { ingredient: "Japansk soja", amount: "2", unit: "msk" },
      { ingredient: "Limejuice", amount: "1", unit: "msk" },
    ],
  },
  {
    title: "Röd chili med skaldjur",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "1. Mixa paste av ingefära, koriander, kaffirlimeblad, sesamolja, soja, fisksås, honung, lime, vitlök, chili och citrongräs.\n2. Blanda halva pasten i vatten och buljong. Marinera skaldjur och svamp i andra halvan.\n3. Koka buljongen. Strimla grönsaker. Tillsätt grönsaker och nudlar, koka 3 min.\n4. Grilla skaldjur och svamp. Lägg ihop alla ingredienser med färsk koriander.",
    ingredients: [
      { ingredient: "Ingefära", amount: "1", unit: "bit" },
      { ingredient: "Koriander", amount: "1", unit: "kruka" },
      { ingredient: "Kaffirlimeblad", amount: "6", unit: "st" },
      { ingredient: "Sesamolja", amount: "1", unit: "msk" },
      { ingredient: "Soja", amount: "1", unit: "msk" },
      { ingredient: "Fisksås", amount: "1", unit: "msk" },
      { ingredient: "Honung", amount: "1", unit: "msk" },
      { ingredient: "Lime", amount: "1", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "2", unit: "st" },
      { ingredient: "Röd chili", amount: "1", unit: "st" },
      { ingredient: "Citrongräs", amount: "1", unit: "st" },
      { ingredient: "Råa skalade räkor", amount: "200", unit: "g" },
      { ingredient: "Bläckfisk", amount: "1", unit: "st" },
      { ingredient: "Äggnudlar", amount: null, unit: null },
      { ingredient: "Diverse grönsaker", amount: null, unit: null },
    ],
  },
  {
    title: "Sesampanerad tonfisk",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions:
      "Blanda sesamfrön, curry, salt och peppar. Vänd tonfisken i blandningen. Stek 1-2 min per sida i rapsolja på hög värme. Tonfisken ska vara rå inuti. Skiva på bräda. Skiva blomkål, krydda med vitlök/chili och örter, stek i olivolja. Yoghurtsås: blanda gurka, yoghurt, koriander och lime. Servera med sallad.",
    ingredients: [
      { ingredient: "Blomkål", amount: "500", unit: "g" },
      { ingredient: "Vitlöksklyfta", amount: "1", unit: "st" },
      { ingredient: "Ingefära", amount: "1", unit: "msk" },
      { ingredient: "Curry", amount: "1", unit: "tsk" },
      { ingredient: "Olivolja", amount: "4", unit: "msk" },
      { ingredient: "Gurka", amount: "½", unit: "st" },
      { ingredient: "Yoghurt", amount: "2", unit: "dl" },
      { ingredient: "Koriander", amount: "2", unit: "msk" },
      { ingredient: "Lime", amount: "1", unit: "st" },
      { ingredient: "Sesamfrön", amount: null, unit: null },
    ],
  },
  {
    title: "Sesampanerad tonfisk med chilimajonnäs",
    category: "Huvudrätter",
    description: "Färsk tonfisk hastigt stekt med sojamarinerad sallad och het chilimajonnäs.",
    servings: null,
    instructions:
      "Sallad: Riv morötter, strimla pak choi och sockerärter. Hacka tomater och örter. Blanda med soja, honung och vinäger. Chilimajonnäs: blanda majonnäs med tabasco och chiliflakes. Blanda sesamfrön, curry, salt och peppar. Vänd tonfisken och stek hastigt på hög värme i rapsolja. Servera ihop.",
    ingredients: [
      { ingredient: "Tonfiskfilé", amount: "900", unit: "g" },
      { ingredient: "Sesamfrön", amount: "¾", unit: "dl" },
      { ingredient: "Curry", amount: "½", unit: "tsk" },
      { ingredient: "Morötter", amount: "9", unit: "st" },
      { ingredient: "Pak choi", amount: "250", unit: "g" },
      { ingredient: "Sockerärter", amount: "150", unit: "g" },
      { ingredient: "Tomater", amount: "3", unit: "st" },
      { ingredient: "Koriander", amount: "1", unit: "kruka" },
      { ingredient: "Thaibasilika", amount: "1", unit: "kruka" },
      { ingredient: "Ljus soja", amount: "1", unit: "dl" },
      { ingredient: "Honung", amount: "1½", unit: "msk" },
      { ingredient: "Risvinäger", amount: "3", unit: "msk" },
      { ingredient: "Majonnäs", amount: "1½", unit: "dl" },
      { ingredient: "Tabasco", amount: "2", unit: "tsk" },
      { ingredient: "Chiliflakes", amount: "1", unit: "tsk" },
    ],
  },
  {
    title: "Smörgåstårta",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "Lager 1: Philadelphia och skinka. Lager 2: Gurkmajonnäs. Lager 3: Skagenröra (hackade räkor, crème fraiche, majonnäs, dill, citronpeppar). Täck med philadelphia, crème fraiche och rostbiff. Dekorera med sallad, ost, brieost, tomater, gurka, citron, melon, physalis och räkor.",
    ingredients: [
      { ingredient: "Philadelphiaost", amount: null, unit: null },
      { ingredient: "Skinka", amount: null, unit: null },
      { ingredient: "Gurkmajonnäs", amount: null, unit: null },
      { ingredient: "Räkor, hackade", amount: null, unit: null },
      { ingredient: "Crème fraiche", amount: null, unit: null },
      { ingredient: "Majonnäs", amount: null, unit: null },
      { ingredient: "Dill", amount: null, unit: null },
      { ingredient: "Citronpeppar", amount: null, unit: null },
      { ingredient: "Rostbiff", amount: null, unit: null },
    ],
  },
  {
    title: "Sojamarinerad lax på spett",
    category: "Huvudrätter",
    description: "Snabblagat men lyxigt, serverat på japanskt vis.",
    servings: 4,
    instructions:
      "Skär bort skinn från laxen. Skär i 2 cm strimlor. Rör ihop marinad av soja, sesamolja, ingefära, socker och wasabi. Marinera laxen. Sås: blanda japansk soja, socker och wasabi. Torka av laxen, trä på spett. Grilla någon minut per sida. Strö sesamfrön. Servera med sushiris.",
    ingredients: [
      { ingredient: "Benfri laxfilé", amount: "600", unit: "g" },
      { ingredient: "Sesamfrön", amount: "2", unit: "msk" },
      { ingredient: "Kinesisk soja", amount: "4", unit: "msk" },
      { ingredient: "Sesamolja", amount: "2", unit: "msk" },
      { ingredient: "Malen ingefära", amount: "1", unit: "msk" },
      { ingredient: "Socker", amount: "1", unit: "msk" },
      { ingredient: "Wasabi", amount: "2", unit: "tsk" },
      { ingredient: "Japansk soja (sås)", amount: "1", unit: "dl" },
      { ingredient: "Sushiris", amount: null, unit: null },
    ],
  },
  {
    title: "Souvlakia",
    category: "Huvudrätter",
    description: "I stället för grillkorv!",
    servings: 8,
    instructions:
      "1. Rör ut jästen i vatten. Tillsätt salt, peppar och mjöl. Arbeta till smidig deg. Jäs 1 timme.\n2. Skär kycklingen i bitar, trä på spett, krydda.\n3. Dela degen i 16 bitar, kavla ut tunt, stek i olja 1 min per sida.\n4. Grilla kycklingen 5 min per sida.\n5. Tsatsiki: riv gurka, salta, blanda med yoghurt, vitlök, citronsaft och olivolja.\nServera kyckling i bröd med tomat, sallad och tsatsiki.",
    ingredients: [
      { ingredient: "Jäst", amount: "25", unit: "g" },
      { ingredient: "Vatten", amount: "2", unit: "dl" },
      { ingredient: "Salt", amount: "1", unit: "tsk" },
      { ingredient: "Vetemjöl", amount: "6", unit: "dl" },
      { ingredient: "Kycklingfiléer", amount: "6-8", unit: "st" },
      { ingredient: "Gurka", amount: "½-1", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "1-2", unit: "st" },
      { ingredient: "Grekisk yoghurt", amount: "3-4", unit: "dl" },
      { ingredient: "Citronjuice", amount: "1", unit: "tsk" },
      { ingredient: "Svarta oliver", amount: null, unit: null },
      { ingredient: "Mynta", amount: null, unit: null },
    ],
  },
  {
    title: "Stekt blomkål i skivor",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "Ugn. Lägg blomkålsskivor på bakplåtspapper. Blanda kryddpasta av finhackad vitlök, finriven ingefära, curry, salt, peppar och olja. Häll över blomkålen, gnid in. Ugnsbaka ca 15 min tills fin färg men rå kärna kvar. Yoghurtsås: blanda gurka, yoghurt, koriander och limesaft. Servera med ris/bulgur/quinoa och sallad.",
    ingredients: [
      { ingredient: "Blomkål", amount: null, unit: null },
      { ingredient: "Vitlök", amount: null, unit: null },
      { ingredient: "Finriven ingefära", amount: null, unit: null },
      { ingredient: "Curry", amount: null, unit: null },
      { ingredient: "Olja", amount: null, unit: null },
      { ingredient: "Gurka", amount: null, unit: null },
      { ingredient: "Yoghurt", amount: null, unit: null },
      { ingredient: "Koriander", amount: null, unit: null },
      { ingredient: "Limesaft", amount: null, unit: null },
    ],
  },
  {
    title: "Stekt getost på salladsbädd",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions:
      "Hacka sallad fint, lägg på tallrikar. Skär getost i centimetertjocka skivor. Doppa i vetemjöl, uppvispat ägg och sedan ströbröd. Stek i rikligt smör tills gyllenbruna. Lägg på salladsbädden. Ringla ev lite honung om smaken är stark.",
    ingredients: [
      { ingredient: "Getost (rulle)", amount: null, unit: null },
      { ingredient: "Sallad (isbergs/roman/huvud)", amount: null, unit: null },
      { ingredient: "Ägg", amount: "1", unit: "st" },
      { ingredient: "Ströbröd", amount: null, unit: null },
      { ingredient: "Vetemjöl", amount: null, unit: null },
      { ingredient: "Smör", amount: null, unit: null },
      { ingredient: "Honung (valfritt)", amount: null, unit: null },
    ],
  },
  {
    title: "Thailändsk slaw med jordnötter",
    category: "Huvudrätter",
    description: "Mums till karré och spjäll.",
    servings: 4,
    instructions:
      "Finstrimla vitkål. Grovriv morot. Blanda finhackad chili, vitlök, socker, limejuice, fisksås och rapsolja. Rör tills sockret lösts. Blanda kål och morot med dressingen. Tillsätt hackad koriander och strö över grovhackade torrostade jordnötter.",
    ingredients: [
      { ingredient: "Färsk vitkål", amount: "300", unit: "g" },
      { ingredient: "Morot", amount: "1", unit: "st" },
      { ingredient: "Röd chili", amount: "1", unit: "st" },
      { ingredient: "Vitlöksklyfta", amount: "1", unit: "st" },
      { ingredient: "Socker", amount: "1", unit: "msk" },
      { ingredient: "Limejuice", amount: "3", unit: "msk" },
      { ingredient: "Fisksås", amount: "2½", unit: "msk" },
      { ingredient: "Rapsolja", amount: "4", unit: "msk" },
      { ingredient: "Koriander", amount: "½", unit: "kruka" },
      { ingredient: "Torrostade jordnötter", amount: "3", unit: "msk" },
    ],
  },
  {
    title: "Torsk med oliver och kronärtskocka",
    category: "Huvudrätter",
    description: null,
    servings: 4,
    instructions:
      "1. Ugn 200°C. Strimla tinad torsk. Dela krabbpinnar i bitar. Häll av kronärtskocksbottnar, dela i bitar. Grovhacka oliver.\n2. Blanda med tärnad feta, olja, citronjuice, salt och peppar.\n3. Olja folieark, fördela blandningen, vik ihop.\n4. Koka basmatiris. Grädda paket 12 min.\n5. Servera på ris med grovhackad persilja.",
    ingredients: [
      { ingredient: "Fryst torsk, tinad", amount: "400", unit: "g" },
      { ingredient: "Krabbpinnar", amount: "150", unit: "g" },
      { ingredient: "Kronärtskocksbottnar", amount: "400", unit: "g" },
      { ingredient: "Svarta oliver", amount: "240", unit: "g" },
      { ingredient: "Tärnad fetaost", amount: "400", unit: "g" },
      { ingredient: "Olivolja", amount: "1", unit: "msk" },
      { ingredient: "Citronjuice", amount: "1", unit: "msk" },
      { ingredient: "Persilja", amount: "1", unit: "dl" },
      { ingredient: "Basmatiris", amount: "4", unit: "port" },
    ],
  },
  {
    title: "Ugnsbakad kall lax",
    category: "Huvudrätter",
    description: "Serveras kall med kall sås och nykokt färskpotatis.",
    servings: null,
    instructions:
      "Blanda kryddblandning av vitlökspulver, muskot, citronpeppar, salt, purjolök och hackad dill. Fördela halva på folie, lägg laxen ovanpå, resten ovanpå och inuti. Gör paket. Grädda 225°C ca 45 min. Låt svalna i paketet, kyl över natten. Sås: blanda majonnäs, gräddfil, vispad grädde, dill, citronpeppar och salt.",
    ingredients: [
      { ingredient: "Hel lax, urtagen", amount: "1", unit: "st" },
      { ingredient: "Vitlökspulver", amount: "1", unit: "krm" },
      { ingredient: "Muskotnöt", amount: null, unit: null },
      { ingredient: "Citronpeppar", amount: null, unit: null },
      { ingredient: "Purjolökar", amount: "1-2", unit: "st" },
      { ingredient: "Dill", amount: "1", unit: "knippe" },
      { ingredient: "Majonnäs (sås)", amount: "3", unit: "dl" },
      { ingredient: "Gräddfil (sås)", amount: "1½", unit: "dl" },
      { ingredient: "Vispgrädde (sås)", amount: "1½", unit: "dl" },
      { ingredient: "Hackad dill (sås)", amount: "2", unit: "dl" },
    ],
  },
  {
    title: "Ugnslagad lax",
    category: "Huvudrätter",
    description: "Dubbel familjeportion.",
    servings: null,
    instructions:
      "Lägg laxfilé i form. Koka upp grädde och crème fraiche med citronskal och buljong. Koka några minuter. Häll över laxen, strö riven parmesan. Baka 225°C i 30 min, täck med bakplåtspapper efter 20 min.",
    ingredients: [
      { ingredient: "Lax", amount: "1,6", unit: "kg" },
      { ingredient: "Grädde", amount: "4", unit: "dl" },
      { ingredient: "Crème fraiche", amount: "4", unit: "dl" },
      { ingredient: "Rivet citronskal", amount: "1", unit: "citron" },
      { ingredient: "Fiskbuljongtärningar", amount: "2", unit: "st" },
      { ingredient: "Riven parmesan", amount: null, unit: null },
    ],
  },
  {
    title: "Vitlöks- och pepparkyckling",
    category: "Huvudrätter",
    description: "Superenkel och magiskt god wok.",
    servings: null,
    instructions:
      "1. Sätt på jasminris.\n2. Häll olja i het wokpanna, fräs skivad vitlök.\n3. Lägg i strimlad kyckling, stek gyllenbrun.\n4. Krydda med fisksås och ostronsås. Smaka av.\n5. Riv över holy basil och strö fried garlic.\n6. Woka broccoli separat med soja, ostronsås och socker. Servera ihop med ris.",
    ingredients: [
      { ingredient: "Kycklingfiléer, strimlade", amount: "4", unit: "st" },
      { ingredient: "Vitlök (tunt skivad)", amount: "10", unit: "klyftor" },
      { ingredient: "Jordnötsolja", amount: "3-5", unit: "msk" },
      { ingredient: "Fisksås", amount: "2½", unit: "msk" },
      { ingredient: "Ostronsås", amount: "2½", unit: "msk" },
      { ingredient: "Socker", amount: "2", unit: "tsk" },
      { ingredient: "Torkad vitlök", amount: "4-8", unit: "msk" },
      { ingredient: "Holy basil", amount: "1", unit: "knippe" },
      { ingredient: "Svartpeppar", amount: null, unit: null },
      { ingredient: "Broccoli", amount: "2", unit: "stånd" },
    ],
  },
  {
    title: "Världens godaste plättar",
    category: "Huvudrätter",
    description: null,
    servings: null,
    instructions: "Mixa allt utom äpplena, rör i dem sist. Stek som plättar.",
    ingredients: [
      { ingredient: "Ägg", amount: "6", unit: "st" },
      { ingredient: "Mjölk", amount: "1", unit: "liter" },
      { ingredient: "Vetemjöl", amount: "5", unit: "dl" },
      { ingredient: "Dinkel fullkorn", amount: "1", unit: "dl" },
      { ingredient: "Sojamjöl", amount: "1,5", unit: "dl" },
      { ingredient: "Rivna morötter", amount: "2", unit: "st" },
      { ingredient: "Rivna äpplen", amount: "2", unit: "st" },
      { ingredient: "Bananer", amount: "3", unit: "st" },
      { ingredient: "Rapsolja", amount: null, unit: "msk" },
      { ingredient: "Salt", amount: null, unit: null },
    ],
  },

  // ═══ SOPPOR ═══
  {
    title: "Blomkålssoppa med bacon och ruccolaolja",
    category: "Soppor",
    description: null,
    servings: 4,
    instructions:
      "Ugn 175°C. Rosta blomkålsbuketter 15 min. Värm rapsolja till 60°C, mixa med ruccola, sila. Fräs potatis, lök, vitlök och purjolök. Tillsätt blomkål och vin, koka in. Tillsätt buljong, sjud 20 min. Mixa slät, tillsätt grädde, citronsaft, salt och peppar. Knaperstek bacon. Servera med bacon, rostblomkål, parmesan och ruccolaolja.",
    ingredients: [
      { ingredient: "Blomkålshuvud", amount: "1", unit: "st" },
      { ingredient: "Potatisar, mjöliga", amount: "4", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "4", unit: "st" },
      { ingredient: "Purjolök", amount: "½", unit: "st" },
      { ingredient: "Vitt vin", amount: "2", unit: "dl" },
      { ingredient: "Buljong", amount: "1", unit: "liter" },
      { ingredient: "Vispgrädde", amount: "3", unit: "dl" },
      { ingredient: "Citron", amount: "½", unit: "st" },
      { ingredient: "Bacon", amount: "140", unit: "g" },
      { ingredient: "Ruccola", amount: "65", unit: "g" },
      { ingredient: "Rapsolja", amount: "2", unit: "dl" },
    ],
  },
  {
    title: "Blomkålssoppa med vitlöksbaguette",
    category: "Soppor",
    description: null,
    servings: 4,
    instructions:
      "1. Hacka lök, skär blomkål. Fräs löken i smör, tillsätt blomkål och kummin. Häll på mjölk och grädde med buljong. Koka 10 min. Mixa slät.\n2. Vitlöksbaguette: Rör ihop smör med hackad vitlök och persilja. Skiva baguette, bred mellan skivorna. Grilla i 250°C 2-5 min.",
    ingredients: [
      { ingredient: "Gula lökar", amount: "2", unit: "st" },
      { ingredient: "Blomkålshuvud", amount: "1", unit: "st" },
      { ingredient: "Kummin", amount: "2", unit: "krm" },
      { ingredient: "Mjölk", amount: "4-5", unit: "dl" },
      { ingredient: "Vispgrädde", amount: "3", unit: "dl" },
      { ingredient: "Grönsaksbuljongtärningar", amount: "3", unit: "st" },
      { ingredient: "Morot", amount: "1", unit: "st" },
      { ingredient: "Baguette", amount: "1", unit: "st" },
      { ingredient: "Vitlöksklyftor", amount: "3", unit: "st" },
      { ingredient: "Smör", amount: "50", unit: "g" },
      { ingredient: "Persilja", amount: "½", unit: "dl" },
    ],
  },
  {
    title: "Fänkål- och morotssoppa med apelsin",
    category: "Soppor",
    description: null,
    servings: 4,
    instructions:
      "Ansa fänkål, skala morötter, skär i bitar. Fräs i smör med vitlök. Täck med vatten, salta och peppra. Sjud 20 min. Mixa slät. Tillsätt apelsinsaft och grädde. Servera med fänkålsvippor, apelsinfiléer eller rostade nötter.",
    ingredients: [
      { ingredient: "Fänkål", amount: "3", unit: "st" },
      { ingredient: "Morötter", amount: "8", unit: "st" },
      { ingredient: "Smör", amount: "2", unit: "msk" },
      { ingredient: "Vitlöksklyftor", amount: "2", unit: "st" },
      { ingredient: "Vatten", amount: "1,2", unit: "liter" },
      { ingredient: "Buljongtärningar", amount: "3", unit: "st" },
      { ingredient: "Chili", amount: null, unit: null },
      { ingredient: "Vitt vin", amount: "2", unit: "dl" },
      { ingredient: "Apelsinsaft", amount: "1", unit: "dl" },
      { ingredient: "Grädde", amount: "3", unit: "dl" },
    ],
  },
  {
    title: "Gulaschsoppa från Österrike",
    category: "Soppor",
    description: null,
    servings: 4,
    instructions:
      "1. Hacka lök och vitlök. Bryn med kött i margarin 5-6 min. Tillsätt tomatpuré och kryddor.\n2. Tillsätt vatten, salt, buljong och citronskal. Sjud 1 timme (med tärnat kött).\n3. Tillsätt tärnad potatis och paprika, koka 30 min till.\n4. Smaka av med paprikapulver, peppar, cayennepeppar. Servera med grovt bröd och crème fraiche.",
    ingredients: [
      { ingredient: "Nötfärs/älgfärs (eller nötkött)", amount: "500", unit: "g" },
      { ingredient: "Gula lökar", amount: "2", unit: "st" },
      { ingredient: "Vitlöksklyfta", amount: "1", unit: "st" },
      { ingredient: "Margarin", amount: "1½", unit: "msk" },
      { ingredient: "Tomatpuré", amount: "2-3", unit: "msk" },
      { ingredient: "Paprikapulver", amount: "2", unit: "tsk" },
      { ingredient: "Mejram", amount: "½", unit: "tsk" },
      { ingredient: "Kummin", amount: "2", unit: "kryddmått" },
      { ingredient: "Vatten", amount: "1¼", unit: "liter" },
      { ingredient: "Köttbuljongtärningar", amount: "3", unit: "st" },
      { ingredient: "Citronskal", amount: "¼", unit: "citron" },
      { ingredient: "Potatisar", amount: "5", unit: "st" },
      { ingredient: "Gröna paprikor", amount: "2", unit: "st" },
    ],
  },
  {
    title: "Gräddig räksoppa",
    category: "Soppor",
    description: null,
    servings: null,
    instructions:
      "1. Finhacka lök, riv selleri. Fräs i smör 5-6 min. Skala räkor, spara skal. Fräs skalen i smör, tillsätt vatten och koka ur. Sila.\n2. Häll räkfond i grytan med grädde och ev fisk. Tillsätt fiskfond/-buljong.\n3. Koka 10 min. Smaka av med salt, peppar och cayennepeppar.\n4. Före servering: värm vinet med räkorna (koka ej), häll i soppan. Servera genast.",
    ingredients: [
      { ingredient: "Räkor med skal", amount: "500", unit: "g" },
      { ingredient: "Gul lök", amount: "1", unit: "st" },
      { ingredient: "Rotselleri", amount: "1", unit: "knytnäve" },
      { ingredient: "Smör", amount: null, unit: "msk" },
      { ingredient: "Vetemjöl", amount: "3", unit: "msk" },
      { ingredient: "Kaffegrädde", amount: "5", unit: "dl" },
      { ingredient: "Vitt vin", amount: "3", unit: "dl" },
      { ingredient: "Fiskfond", amount: null, unit: null },
      { ingredient: "Cayennepeppar", amount: null, unit: null },
    ],
  },
  {
    title: "Hummersoppa",
    category: "Soppor",
    description: null,
    servings: null,
    instructions:
      "1. Rosta krossat hummerskal med tomatpuré och grönsaker i 200°C i 30 min. Fräs i smör 5 min.\n2. Tillsätt vatten och vin, koka under lock 45 min, sila.\n3. Tillsätt grädde, cayennepeppar och cognac, reducera 15 min.\n4. Smaka av med salt, peppar och fond. Red till lagom konsistens. Servera med hummerbitar och fänkål.",
    ingredients: [
      { ingredient: "Hummarskal", amount: "2-4", unit: "humrar" },
      { ingredient: "Tomatpuré", amount: "4", unit: "msk" },
      { ingredient: "Gul lök", amount: "1", unit: "st" },
      { ingredient: "Morot", amount: "1", unit: "st" },
      { ingredient: "Rotselleri", amount: "1", unit: "bit" },
      { ingredient: "Stjälkselleri", amount: "1", unit: "st" },
      { ingredient: "Fänkål", amount: "1", unit: "st" },
      { ingredient: "Smör", amount: "100", unit: "g" },
      { ingredient: "Vatten", amount: "1", unit: "liter" },
      { ingredient: "Vitt vin", amount: "2", unit: "dl" },
      { ingredient: "Cognac", amount: "½", unit: "dl" },
      { ingredient: "Grädde", amount: "4-5", unit: "dl" },
      { ingredient: "Cayennepeppar", amount: null, unit: null },
    ],
  },
  {
    title: "Klassisk löksoppa",
    category: "Soppor",
    description: "En riktig vinterklassiker.",
    servings: 4,
    instructions:
      "1. Skala, halvera och skiva löken. Fräs all lök med socker i olivolja 15 min. Löken ska inte få färg.\n2. Tillsätt timjan, mejram, fond, vin och vatten. Koka under lock 15 min. Smaka av med salt och peppar.",
    ingredients: [
      { ingredient: "Gula lökar", amount: "7", unit: "st" },
      { ingredient: "Socker", amount: "2", unit: "tsk" },
      { ingredient: "Torkad timjan", amount: "2", unit: "tsk" },
      { ingredient: "Torkad mejram", amount: "1½", unit: "tsk" },
      { ingredient: "Konc grönsaksfond", amount: "½", unit: "dl" },
      { ingredient: "Vitt vin", amount: "½", unit: "dl" },
      { ingredient: "Vatten", amount: "1¼", unit: "liter" },
      { ingredient: "Olivolja", amount: "3", unit: "msk" },
    ],
  },
  {
    title: "Kycklingsoppa",
    category: "Soppor",
    description: null,
    servings: null,
    instructions:
      "Koka äggnudlar. Koka upp vatten med hönsbuljongtärningar. Tillsätt sweet chilisås, soja och sesamolja. Plocka kött från halv grillad kyckling, blanda ner med nudlar. Sjud 1 min. Rör ner hackad koriander och strimlad purjolök. Servera i soppskålar.",
    ingredients: [
      { ingredient: "Äggnudlar", amount: "200", unit: "g" },
      { ingredient: "Vatten", amount: "1", unit: "liter" },
      { ingredient: "Hönsbuljongtärningar", amount: "2", unit: "st" },
      { ingredient: "Sweet chilisås", amount: "4", unit: "msk" },
      { ingredient: "Soja", amount: "1", unit: "msk" },
      { ingredient: "Sesamolja", amount: "½", unit: "tsk" },
      { ingredient: "Halvt grillad kyckling", amount: "½", unit: "st" },
      { ingredient: "Koriander", amount: "1", unit: "dl" },
      { ingredient: "Purjolök, strimlad", amount: "2", unit: "dl" },
    ],
  },
  {
    title: "Löksoppa (Tarte à l'oignon)",
    category: "Soppor",
    description: "En äkta fransk lökpaj.",
    servings: 4,
    instructions:
      "1. Hacka ihop mjöl och matfett. Tillsätt äggula och vatten, arbeta ihop. Vila 1 timme.\n2. Fräs hackad lök i matfett minst 10 min utan färg. Kavla ut degen, kläd pajform.\n3. Blanda löken med ägg, riven ost och kryddor. Häll i formen.\n4. Grädda 200°C ca 40 min tills fin färg.",
    ingredients: [
      { ingredient: "Vetemjöl", amount: "3½", unit: "dl" },
      { ingredient: "Smör", amount: "100", unit: "g" },
      { ingredient: "Äggula", amount: "1", unit: "st" },
      { ingredient: "Kallt vatten", amount: "3", unit: "msk" },
      { ingredient: "Stora gula lökar", amount: "5", unit: "st" },
      { ingredient: "Ägg", amount: "3", unit: "st" },
      { ingredient: "Riven ost", amount: "50", unit: "g" },
      { ingredient: "Vitpeppar", amount: "1", unit: "krm" },
      { ingredient: "Muskotnöt", amount: null, unit: null },
    ],
  },
  {
    title: "Nongs super syrliga räksoppa",
    category: "Soppor",
    description: null,
    servings: null,
    instructions:
      "1. Koka upp buljong med röd curry, galangal, chili och citrongräs. Puttra 10 min.\n2. Krydda med fisksås, socker, lime, limeblad och kokosgrädde. Puttra.\n3. Tillsätt räkor, tomater och svamp. Koka tills räkorna är rosa.\n4. Dekorera med vårlök och koriander.",
    ingredients: [
      { ingredient: "Grönsaksbuljong", amount: "1", unit: "liter" },
      { ingredient: "Röd currypasta", amount: "2", unit: "msk" },
      { ingredient: "Citrongräs", amount: "4", unit: "st" },
      { ingredient: "Galangal", amount: "5", unit: "cm" },
      { ingredient: "Krossad chili", amount: "2", unit: "st" },
      { ingredient: "Fisksås", amount: "3⅓", unit: "msk" },
      { ingredient: "Limeblad", amount: "8", unit: "st" },
      { ingredient: "Lime", amount: "1½", unit: "st" },
      { ingredient: "Kokosgrädde", amount: "2½", unit: "dl" },
      { ingredient: "Körsbärstomater", amount: "10", unit: "st" },
      { ingredient: "Råa tigerräkor", amount: "10", unit: "st" },
      { ingredient: "Champinjoner", amount: "6-10", unit: "st" },
      { ingredient: "Vårlök", amount: "4", unit: "st" },
      { ingredient: "Koriander", amount: "1", unit: "knippe" },
    ],
  },
  {
    title: "Potatis- och purjolökssoppa",
    category: "Soppor",
    description: null,
    servings: null,
    instructions:
      "Skär grönsakerna fint. Fräs i olivolja utan färg. Tillsätt vatten och buljongtärningar. Koka 15-20 min tills potatisen är sönderkokt. Vispa slät och red med grädde. Smaka av med salt och peppar.",
    ingredients: [
      { ingredient: "Potatisar", amount: "4-5", unit: "st" },
      { ingredient: "Gul lök", amount: "1", unit: "st" },
      { ingredient: "Purjolökar", amount: "3-4", unit: "st" },
      { ingredient: "Vatten", amount: "1", unit: "liter" },
      { ingredient: "Buljongtärningar", amount: "2", unit: "st" },
      { ingredient: "Grädde eller crème fraiche", amount: "2", unit: "msk" },
      { ingredient: "Olivolja", amount: null, unit: null },
    ],
  },
  {
    title: "Tom Kha Goong",
    category: "Soppor",
    description: null,
    servings: null,
    instructions:
      "1. Stek schalottenlök och ev färska chili. Banka citrongräset. Häll på buljong, ingefära, limeblad, finhackad chili och fisksås. Koka upp, lägg i svampen och koriandern. Koka några minuter.\n2. Tillsätt räkor och koka upp. Smaksätt med limesaft och korianderblad. Man kan ha i morot, broccoli, paprika för matigare soppa.",
    ingredients: [
      { ingredient: "Champinjoner", amount: "150-200", unit: "g" },
      { ingredient: "Jätteräkor", amount: "500", unit: "g" },
      { ingredient: "Vatten", amount: "1½", unit: "liter" },
      { ingredient: "Kycklingbuljongtärningar", amount: "2-3", unit: "st" },
      { ingredient: "Koriander", amount: "1", unit: "kruka" },
      { ingredient: "Kaffirlimeblad", amount: "3", unit: "st" },
      { ingredient: "Citrongräs", amount: "2", unit: "st" },
      { ingredient: "Ingefära", amount: "5", unit: "cm" },
      { ingredient: "Torkade chilis", amount: "2-3", unit: "st" },
      { ingredient: "Limesaft", amount: "4", unit: "msk" },
      { ingredient: "Fisksås", amount: "4", unit: "msk" },
      { ingredient: "Schalottenlökar", amount: "2", unit: "st" },
    ],
  },

  // ═══ EFTERRÄTTER ═══
  {
    title: "Ananaspaj",
    category: "Efterrätter",
    description: null,
    servings: null,
    instructions:
      "Pajskal: Blanda ihop mjöl, socker, margarin och bakpulver (enklast i matberedare). Tryck ut i pajform. Fyllning: Rör ihop crème fraiche, ägg, socker och vaniljsocker. Lägg fyllningen i skalet. Grädda 175°C i 35 min. Servera med vispad grädde eller vaniljglass.",
    ingredients: [
      { ingredient: "Vetemjöl (pajskal)", amount: "3", unit: "dl" },
      { ingredient: "Socker (pajskal)", amount: "1", unit: "dl" },
      { ingredient: "Margarin", amount: "150", unit: "g" },
      { ingredient: "Bakpulver", amount: "1", unit: "tsk" },
      { ingredient: "Crème fraiche", amount: "1", unit: "burk" },
      { ingredient: "Ägg", amount: "1", unit: "st" },
      { ingredient: "Socker (fyllning)", amount: "½", unit: "dl" },
      { ingredient: "Vaniljsocker", amount: "2", unit: "tsk" },
      { ingredient: "Krossad ananas (eller färska bär)", amount: "1", unit: "burk" },
    ],
  },

  // ═══ BAKVERK ═══
  {
    title: "Ett stort bröd",
    category: "Bakverk",
    description: null,
    servings: null,
    instructions:
      "1. Blanda mjölk, torrjäst, mjöl och socker. Jäs 30 min.\n2. Blanda i vatten, olivolja, salt och resterande mjöl. Jäs 30 min till.\n3. Baka ut degen till rund form. Jäs under duk 45 min.\n4. Pensla med ägg, strö sesamfrön eller nigellafrön. Grädda 200°C i 20 min.",
    ingredients: [
      { ingredient: "Varm mjölk", amount: "200", unit: "g" },
      { ingredient: "Torrjäst", amount: "10", unit: "g" },
      { ingredient: "Vetemjöl (del 1)", amount: "120", unit: "g" },
      { ingredient: "Socker", amount: "4", unit: "g" },
      { ingredient: "Vatten", amount: "245", unit: "g" },
      { ingredient: "Olivolja", amount: "40", unit: "g" },
      { ingredient: "Salt", amount: "8", unit: "g" },
      { ingredient: "Vetemjöl (del 2)", amount: "415", unit: "g" },
      { ingredient: "Sesamfrön eller nigellafrön", amount: null, unit: null },
    ],
  },
  {
    title: "Gudomliga skorpor",
    category: "Bakverk",
    description: null,
    servings: null,
    instructions:
      "Blanda jäst och socker. Värm mjölk och olja till 37°C, häll över. Tillsätt ägg och vetemjöl till lös deg. Arbeta väl. Jäs 30-40 min. Kavla ut ½ cm, strö bakpulver, forma till 48 bullar. Grädda 175°C ca 15 min. Dela med gaffel. Torka 100°C i 45 min, sedan 125°C i 10 min.",
    ingredients: [
      { ingredient: "Jäst", amount: "40", unit: "g" },
      { ingredient: "Ägg", amount: "1", unit: "st" },
      { ingredient: "Socker", amount: "1", unit: "dl" },
      { ingredient: "Mjölk", amount: "3", unit: "dl" },
      { ingredient: "Majsolja", amount: "½", unit: "dl" },
      { ingredient: "Vetemjöl", amount: null, unit: null },
      { ingredient: "Bakpulver", amount: "1", unit: "tsk" },
    ],
  },
  {
    title: "Korvbröd",
    category: "Bakverk",
    description: "Funkar även som hamburgerbröd.",
    servings: 25,
    instructions:
      "1. Blanda alla ingredienser, arbeta 10 min i maskin (20 min för hand). Vila 30 min.\n2. Dela i 25 delar, rulla till 12 cm bröd. Jäs till dubbel storlek ca 1,5 timme.\n3. Grädda 225°C ca 10 min. Frys in de som inte ska användas direkt.",
    ingredients: [
      { ingredient: "Mjölk 3%", amount: "500", unit: "g" },
      { ingredient: "Jäst", amount: "75", unit: "g" },
      { ingredient: "Vetemjöl", amount: "750", unit: "g" },
      { ingredient: "Rumstempererat smör", amount: "50", unit: "g" },
      { ingredient: "Havssalt", amount: "15", unit: "g" },
    ],
  },
  {
    title: "Leilas chocolate cupcakes",
    category: "Bakverk",
    description: "Underbara cupcakes med chokladfrosting. 12 st.",
    servings: 12,
    instructions:
      "1. Ugn 175°C. Vispa ägg, socker och vaniljsocker pösigt. Smält smör, blanda med gräddfil och kaffe.\n2. Blanda mjöl, bakpulver, kakao och salt. Vänd försiktigt ner i smeten.\n3. Smält mörk choklad i vattenbad. Fyll pappersformar till 2/3. Grädda 15 min. Svalna.\n4. Frosting: Rör smör, florsocker, vaniljsocker, kakao och philadelphiaost krämigt. Rör ner kaffe. Bred på cupcakes.",
    ingredients: [
      { ingredient: "Ägg", amount: "3", unit: "st" },
      { ingredient: "Strösocker", amount: "2,5", unit: "dl" },
      { ingredient: "Vaniljsocker", amount: "1", unit: "tsk" },
      { ingredient: "Smör", amount: "50", unit: "g" },
      { ingredient: "Gräddfil", amount: "1", unit: "dl" },
      { ingredient: "Kallt kaffe", amount: "2", unit: "msk" },
      { ingredient: "Vetemjöl", amount: "3-5", unit: "dl" },
      { ingredient: "Bakpulver", amount: "2", unit: "tsk" },
      { ingredient: "Kakao", amount: "4", unit: "msk" },
      { ingredient: "Mörk choklad 70%", amount: "100", unit: "g" },
      { ingredient: "Mjukt smör (frosting)", amount: "60", unit: "g" },
      { ingredient: "Florsocker (frosting)", amount: "5", unit: "dl" },
      { ingredient: "Kakao (frosting)", amount: "½", unit: "dl" },
      { ingredient: "Philadelphiaost (frosting)", amount: "100", unit: "g" },
    ],
  },
  {
    title: "Mormors saftiga äppelkaka",
    category: "Bakverk",
    description: null,
    servings: null,
    instructions:
      "Hacka ihop deg-ingredienserna, vila 30 min i kylskåp. Ugn 200°C. Tryck ut degen i form (24 cm). Skala äpplen, dela, skär i klyftor. Lägg i formen. Vispa ihop crème fraiche, ägg, socker och vaniljsocker, häll över äpplena. Grädda i nedre ugnen ca 25 min tills gyllenbrunt.",
    ingredients: [
      { ingredient: "Vetemjöl (deg)", amount: "2", unit: "dl" },
      { ingredient: "Strösocker (deg)", amount: "1", unit: "msk" },
      { ingredient: "Smör (deg)", amount: "75", unit: "g" },
      { ingredient: "Äggula (deg)", amount: "1", unit: "st" },
      { ingredient: "Äpplen", amount: "3-4", unit: "st" },
      { ingredient: "Crème fraiche", amount: "2", unit: "dl" },
      { ingredient: "Ägg (fyllning)", amount: "2", unit: "st" },
      { ingredient: "Socker (fyllning)", amount: "¾", unit: "dl" },
      { ingredient: "Vaniljsocker", amount: "1", unit: "tsk" },
    ],
  },
  {
    title: "Pâté Brisée - fransk äppelkaka",
    category: "Bakverk",
    description: null,
    servings: 8,
    instructions:
      "Pajdeg: rör ihop mjöl, smör, äggula, salt och vatten. Kavla ut i pajform. Pricka med gaffel, ställ kallt. Mandelkräm: smält smör, rör ner socker. Vispa luftigt. Tillsätt ägg, äggula, calvados, mandlar och mjöl. Häll i kall pajbotten. Skala äpplen, skär tunt, arrangera ovanpå. Grädda 200°C 10-15 min, sänk till 180°C 15-20 min. Strö socker sist. Pensla med smält aprikossylt.",
    ingredients: [
      { ingredient: "Vetemjöl (deg)", amount: "200", unit: "g" },
      { ingredient: "Smör (deg)", amount: "100", unit: "g" },
      { ingredient: "Äggula (deg)", amount: "1", unit: "st" },
      { ingredient: "Salt", amount: "¾", unit: "tsk" },
      { ingredient: "Kallt vatten", amount: "2½", unit: "msk" },
      { ingredient: "Dessertäpplen", amount: "3-4", unit: "st" },
      { ingredient: "Smör (kräm)", amount: "100", unit: "g" },
      { ingredient: "Strösocker (kräm)", amount: "100", unit: "g" },
      { ingredient: "Ägg (kräm)", amount: "1", unit: "st" },
      { ingredient: "Äggula (kräm)", amount: "1", unit: "st" },
      { ingredient: "Calvados", amount: "2", unit: "tsk" },
      { ingredient: "Skållade, malda mandlar", amount: "100", unit: "g" },
      { ingredient: "Vetemjöl (kräm)", amount: "2", unit: "msk" },
      { ingredient: "Aprikossylt", amount: "1½", unit: "dl" },
    ],
  },

  // ═══ ÖVRIGT ═══
  {
    title: "Kräftspad",
    category: "Övrigt",
    description: null,
    servings: null,
    instructions: "Koka upp alla ingredienser och låt svalna.",
    ingredients: [
      { ingredient: "Vatten", amount: "8", unit: "liter" },
      { ingredient: "Salt", amount: "3,5", unit: "dl" },
      { ingredient: "Dillkronor", amount: "3", unit: "st" },
      { ingredient: "Porter", amount: "2-3", unit: "st" },
      { ingredient: "Strösocker", amount: "8", unit: "msk" },
    ],
  },
];

async function main() {
  const familyId = process.argv[2];

  if (!familyId) {
    console.log("Användning: node supabase/seed-missing.mjs <family_id>\n");
    const families = await listFamilies();
    if (families.length === 0) {
      console.log("  (inga familjer)");
    } else {
      for (const f of families) console.log(`  ${f.id}  ${f.name}`);
    }
    process.exit(0);
  }

  const existing = await getExistingTitles(familyId);
  const toInsert = recipes.filter((r) => !existing.has(r.title.toLowerCase().trim()));

  console.log(`Totalt ${recipes.length} recept i skriptet.`);
  console.log(`${existing.size} recept finns redan i databasen.`);
  console.log(`${toInsert.length} nya recept att lägga in.\n`);

  let ok = 0;
  let fail = 0;

  for (const r of toInsert) {
    try {
      const [inserted] = await api("recipes", {
        family_id: familyId,
        title: r.title,
        description: r.description,
        instructions: r.instructions,
        category: r.category,
        source: "Familjen Frosts Kokbok",
        servings: r.servings,
        is_active: true,
      });

      if (r.ingredients.length > 0) {
        await api(
          "recipe_ingredients",
          r.ingredients.map((ing, i) => ({
            recipe_id: inserted.id,
            ingredient: ing.ingredient,
            amount: ing.amount,
            unit: ing.unit,
            sort_order: i,
          })),
        );
      }

      console.log(`  ✓ ${r.title}`);
      ok++;
    } catch (e) {
      console.error(`  ✗ ${r.title}: ${e.message}`);
      fail++;
    }
  }

  console.log(`\nKlart! ${ok} lyckades, ${fail} misslyckades.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
